import React, { createContext, useContext, useReducer } from "react";
import meme from "./images/meme.png";
import babycaller from "./images/babycaller.jpg";
import cpc from "./images/cpc.png";
import akita from "./images/akita.png";
import tromp from "./images/tromp.png";
import pengwifhat from "./images/pengwifhat.png";
import shinhan from "./images/shinhan.png";
import pekachu from "./images/pekachu.png";
import renaldewifhat from "./images/renaldewifhat.png";
import bookofdoge from "./images/bookofdoge.png";
import kingmeme from "./images/kingmeme.png";
import snappe from "./images/snappe.png";
import anapple from "./images/anapple.png";
import mcdonald from "./images/mcdonald.png";
import anpe from "./images/anpe.png";
import pome from "./images/pome.png";
import homer from "./images/homer.png";
import lily from "./images/lily.png";
import bop from "./images/bop.png";
import pepeg from "./images/pepeg.png";
import catwifbag from "./images/catwifbag.png";
import pengisking from "./images/pengisking.png";
import xpidercat from "./images/xpidercat.png";
import meow from "./images/meow.png";
import katking from "./images/katking.png";
import pengwifcat from "./images/pengwifcat.png";
import pella from "./images/pella.png";
import smoly from "./images/smoly.png";
import fineandsmole from "./images/fineandsmole.png";
import benny from "./images/benny.png";
import toby from "./images/toby.png";
import kitcat from "./images/kitcat.png";
import pepebutpurple from "./images/pepebutpurple.png";
import joebomeow from "./images/joebomeow.png";
import quack from "./images/quack.png";
import katcoin from "./images/katcoin.png";
import catkiller from "./images/catkiller.png";
import catgo from "./images/catgo.png";
import china from "./images/china.png";
import sonke from "./images/sonke.png";
import hitler from "./images/hitler.png";
import katpe from "./images/katpe.png";
import mastercat from "./images/mastercat.jpg";
import theone from "./images/theone.jpg";
import dracula from "./images/dracula.jpg";
import mumu from "./images/mumu.jpg";
import wulf from "./images/wulf.jpg";
import weibo from "./images/weibo.jpg";
import MM from "./images/MM.jpg";
import whitePlusIcon from "./images/icons/white-plus-icon-3.png";
import moby from "./images/moby.png";
import panda from "./images/panda.jpg";
import kingkong from "./images/kingkong.jpg";
import travel from "./images/travel.jpg";
import { dataReducer } from "./reducers";

const DataContext = createContext();

export const DataProvider = ({ children }) => {
  const initialDataTemp = [
    {
      id: 13123332,
      table: "hitler",
      name: "World War II",
      logo: hitler,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Weibo Gambles",
          icon: weibo,
          link: "https://t.me/WeiboGambles",
        },
        {
          name: "Wulfden",
          icon: wulf,
          link: "https://t.me/WulfdenX",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "World War II: A historic memecoin on Solana, commemorating the past with a nod to the future. Join the battle for crypto supremacy!",
      min: 1,
      max: 4,
      time: "2024-04-13T12:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/WorldWarIIPortal",
      tw: "https://twitter.com/WorldWarII_X",
      web: "https://ww2onsol.fun/",
    },
    {
      id: 13123332,
      table: "sonke",
      name: "SONKE",
      logo: sonke,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Kong on Chain 🦍",
          icon: kingkong,
          link: "https://t.me/Kong_on_chain",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "SONKE is a degenerate gambler with anger issues on the Solana network.",
      min: 1,
      max: 4,
      time: "2024-04-12T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/SONKESOLPortal",
      tw: "https://twitter.com/SONKE_X",
      web: "https://sonke.fun/",
    },
    {
      id: 13123332,
      table: "catgo",
      name: "CatGo",
      logo: catgo,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Dracula Gamble",
          icon: dracula,
          link: "https://t.me/DraculaGamble",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Meme-ing Our Way to the 'Purr-fect' Search for Crypto Fun!",
      min: 1,
      max: 4,
      time: "2024-04-12T12:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/CatGoChannel",
      tw: "https://twitter.com/CatGoX",
      web: "https://catgo.me/",
    },
    {
      id: 13123332,
      table: "china",
      name: "CHINA",
      logo: china,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "MUMU THE BULL",
          icon: mumu,
          link: "https://t.me/MumuCaller",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "发现中国，创造未来！",
      min: 1,
      max: 4,
      time: "2024-04-11T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/CHINA_ProjectSOL",
      tw: "https://twitter.com/CHINA_ProjectX",
      web: "https://chlnasolana.xyz/",
    },
    {
      id: 13123332,
      table: "catkiller",
      name: "Cat Killer",
      logo: catkiller,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Weibo Gambles",
          icon: weibo,
          link: "https://t.me/WeiboGambles",
        },
        {
          name: "Wulfden",
          icon: wulf,
          link: "https://t.me/WulfdenX",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "猫杀手 - 激起您的野性",
      min: 1,
      max: 4,
      time: "2024-04-11T12:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/CatKillerChannel",
      tw: "https://twitter.com/CatKiller_X",
      web: "https://snakecoln.me/",
    },
    {
      id: 13123332,
      table: "katcoin",
      name: "Katcoin ",
      logo: katcoin,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      whitelists: [
        "DDGw5igDK5wdAFEiDPG6QrVwRoChw93kubyA1EE3oDRn",
        "BMcPXtYobAodWJBwhUZZ6nMiUrSZdjbZJYriJTeHzB8C",
        "6ARDhdqTpU6cVhwrT8bxqA1SqBncFw1tNtAUa2EVvsDg",
        "4oEvW3xqUL7DhsbqLXZgEEMwjVb5keERJ2HXbuc4Roff",
        "2S8Fbe4brX9Abp5zyzLfbHRPoPNntCWw96Uwf9P8xkXf",
        "vGwDoftfevGkhHGHZoEMPuLTUcRe2FmdZigjrZkSGUe",
        "8YBtzhQcUar48wNPqShTxbj7uEehiQqiRgQvcQN34fsd",
        "3SrV6fXBDfLHYJjGgEmuT85cTWzC7wJPu6GXhf97jGtR",
        "CcmYrfxprDtzvcsu1T5M5gUHpqG1UnmbAFB6bQqhcb2J",
        "3CeiK7Sfjup6WgZfjjpV6Vi2NgWarfMH4az4VGJ7CiSy",
        "CFLGGZzFdyfowAwL2GaUJ67zCYztpWRxKyD1vNeLEWQD",
        "69WMNgFtGdwHBQCS1MVRCfnFfNxZMSrjDmD9ZzM3EVx2",
        "C5WJDxhcQfJvqtPNZUZ5j7AkW68arxeEg6U5TLzYNYAW",
        "Gei93EhFT1uZo55Tf1ACMY7SUDRUfMFN5FX3VDBd1vcL",
        "4YPKc7JFvbmWTMpwdMg9UJisJEmpuewKr5rERkZ4BBj7",
        "FmBZSeLyzMjWjYdRYrwYGC8xPSoC243Ga68CkKZPvjmV",
        "CTrzpc1HJopLbxZaWbyLUBzwcaS44jpQ6ERdUqVpLq83",
        "56GpTCTwjasFL55N3KE4nnK2FzrGyybwXAEHTwKpAWv6",
        "FN87ncUSvCyW8LvdCKZwRvbWdgWoxomzxUGKk6EKHafZ",
        "AHQ1bqpHpzmMNzfh49BFk6WdkSG8XRRjZ7ysA7xGzxu5",
        "4UoKjNiCwDd8TKrEdPerPeu71MVAUeUWsnVWYaCD8UuA",
        "HPK1H6RGhBNJqrCN3aPJU86LiqRM6wFGVEtPZLVA3PLi",
        "835WntL7tfhd1V1WjCLGVFNFMTQx3r4nt6veK5CW9rTP",
        "8vTn2jTpiQWSx9aJA2wdkDzpSK7zaTSS6bWr7seeAf6H",
        "FA8NSAwgF1NR2BDkqLEGZBjea1diqG4J48iySNxzrRth",
        "FRo8Revv2LLaJgu3UfGF7qD7ioT9HRRR4nVxvNLvGc18",
        "7TETacfv5znkMPjuD6uTEHBKCNhWAacppXUyDcktx7AZ",
        "88LcTsHg9xsmisYP7mFE5YuDqayuh84UaCM43XELhR7p",
        "2G4Y55R5CV2VYgiyJAqmvkFByNHKwsebyrP7zH7euk5Y",
        "4m88rujoyWNBPuWSaeJGJV9EdsWxBUGmcj7UBMRt3HCt",
        "8RigJvQka2cBRdehdn4Xd1bhF48s1CWE1KoxRRJjDprH",
        "69nuVMFH4vyqoPLQyYAbvuRa8Xm1XQMsHqKiTTsUcSvL",
        "51DwknGfrPZSjBBsAqrg9CToaoXtpvQTG73RmJQ3iLKP",
        "ARf1R51znNXz8DcK5EGsKMVVVfzqLJFLzyup6T5EzvnF",
        "FbNrcf3HRGN3uDkeHZW8Z5DnkR4WgePDu1QjakiZjzJc",
        "3AJP2xES3grpq6yKyeYWo2orzER8wENoJ9aVbunV9hum",
        "48W8JPhyKYF17yU1ULs4gNfxV9WrzMXmhtyEYRNGRSSW",
        "26WnrgzTAQuAMvPrg68oNhyM9kUSe8tjZfPpxKWaBPPy",
        "5aXx1kiYSe8XnaDj5h8jFwBZxGCxXpX4KndQ9TBR8LnA",
        "2CoRQo253f9a97zhx8iZguhC73dxtvbFZxXAuzRqmqZV",
        "78e6JprGXr5rXuQG24Lapqg5Zd2oKf7YT28Vbnr7ucPA",
        "Dt2hQ1pYr3bSAs6mbeBp1QiCUgTpgb26MjdmTXdbRkk1",
        "GV4F3niiD6bziu3AQUMHyRQcuW8Pun52fLoAPkEhLwsB",
        "BhmkoK8zzRk63TMRuNBcLuQVnnLrscSCgidZERJm86BY",
        "G3LYfVghCiBJuTKDoFrdVBeWTKS3aWAPeNaW2kYbS5eT",
        "CM5sEdzqKAncQLVhF6ds89fLCDmxQVfGNAdKtabuBR6U",
        "91jgYNqfEjDMarh8CNwn4Y6vW6gPuNH4P6RLAyexJBzB",
        "HJZrt5PosdDFWqxCuEDPA3FHcsHG7FtwDPksXkwFJpUX",
        "AGy3vX29bCQ6meA8oCxX9cq51ifga2y3dTm66Lj4VsvW",
        "8Lt5rUuJjyD3Z6oisHM4RTe59hkHEyaPtLWkG96V1X8T",
        "7i9xcU8Pzpr3ro45D6ama8149kfjcgkKE9zujTr96o17",
        "HNtQbcv4jrtvcdVBWB2nR1S3UgPeqxKa3KW3iZnKmnH7",
        "A1V4sYgXfN8Dew8FHtb7QXL4Zae3K7a5AeQW7djPrWvP",
        "4RjKzMtSr4KX1VeWmSh4ZokJHdm5d55XNdE9xjS9F43D",
        "7SyZHRGofy4DpE5DqyyF58KgXGiQSspwpHvkc9VWaj4x",
        "ChuLB4SWBaxok779fh8AemXwdrkxUbZ61LJEE6E4Bs9e",
        "28EEYn7qCrVfWLB4ZXEKJHULVPNuEdcEo7523Zpo55s8",
        "9XQQ6TKEM3v8MBag8vgDiGGpgzoCJunguVbqAweoWcCo",
        "AwJWqrXkexnejzYfgpb4ncCre2uxr4a3op57Zn8DMgbj",
        "6wDmvcJBD3nYDC5YwYCz8aWY9dBQrDc6y8Ci8iSDLdE",
        "AEaQf9u7e9EcYgCLpes6GPmAhSc4L25HfrzsTiLmnVxH",
        "Fp7bPy11cEsbpVYNQVBoe4Yyye2FrR3SqHYdKn4LRJj6",
        "3boAHcCpXMgXZhaf3eMC5onUpbNDjd1VV5PkjzMFvgSG",
        "HCoJEgegVBs8n4QmFhp24zZLJWCwwobw1LgkAmDFUht5",
        "89K52GPyVy6oQYeJXSZLRo4pLWfCHkiD53dQLKrfEjo7",
        "AchThfLNw4vMoCUkYD41V8fDkgPPhm6phdcS5fw8EoAr",
        "ECfwEGeLfQ5s58k6HRYRULddrJCziPdw86FXbAqnCmgv",
        "GqoyQ2hQ5qZViQPW7gfFKjrFpAAKWqrX99c3gs8DEhQS",
        "5VzbzvCyncUFRNrABvtMBToHDk3Nmxutj6o1D7tBHjfm",
        "5xA3LaJAjXFccKZs9XyqqsMFmd4Y3tSeAjY8xNdtaeLV",
        "GaqpzLKPbSgZkBsa6bmF5ZuLLhXgpqm1qj9y2uw474JB",
        "9MtNi9AK1ExDiiYBKiY1jwXi8DmFpYeWTwWxnLuAWREQ",
        "4i5p8ySVVk9RZRrfTa88uM9jwmsfGLnwy4A2psvFpLHj",
        "EjufoNUf8saZUGXEYVocbDtgCBx177v1NgaGVv6t2Zf",
        "JBaT1NYoehi3TZKdz2MxUjFPHAqqCTxEPAL8iAbRie3y",
        "FMWrBJaM1gYZmopzQrkYAzKdWv6vnEkVriYC7xbh1kEk",
        "EvBQzpgRnY2ZM3b1QBq1MKoVGuvU7CgJsaP4RmDnVW5V",
        "JYtLbbtQTjGgfCwVDazAXRhVC4quHQkJtiax2FHtJu3",
        "F9VmBpRwmeKYNTyFNUpgTPZf26rzn2rWq9H4rsWrzBTA",
        "27Sd9n5xnwmhapGTRYBKsGDCBh7UTb8xZC8tivYs2fbS",
        "9dYJqG91Su7VrVVFYmWVYoJVwAKMXfMprqZ6HM49s3mp",
        "7bAFWdo59xBQifq5T7H9pYTk6kg2LfXhuxNWoabaGtjS",
        "CXaeBvNXTMcdcFBGzUuUK8JctzvYADCaPqPmNTQbSn3j",
        "9tdCoeHmdc7izb3PDq4Vy6236rDHngEkCMoLXHRtZQak",
        "5U5TFaB3h9YczWS5fz4JH8vymF7rA9QYyChteGytYMe7",
        "GpNyFzbBMTLtpnUFj66CjnV3yWncEY2pZQW88gb9R6VQ",
        "2YF7dTPCYPKzEM1MpQBEwR81AWK6uk13YmowzQCZLZBV",
        "CaNrasuMDhZThNDMvaZDDhC3ioXi7PU7hvAcUpQBwLNJ",
        "6sLJFNaQSPdKNu4x8HtG3KMcoscRmbdWpPHoDB43ZANZ",
        "AcrczRktUbNFK9Whz8XHDeUYKgmhWKpTYRUocCoAXXv3",
        "6oyVmrB2Mmy4RgBxZUqDT4CCkPuK5RyKYsR134syXu7j",
        "FaBFUXyCmgnzpEDQqprNNgUa2Ez2vavdzwsg4p4aTrAg",
        "5QAQFpRgwQAAT8jdyx9NxknsAcunxMD3PE1Jt9BWKaxy",
        "Co9yXjmSJpEoRngjDPJG4JdvS7w5JLGxjFmQ3FYEcDbj",
        "4GveQJnrodGvesLXAa5v4Kor2MY1HuSuVVrrQs2DRypE",
        "Fef1MBRYY3gXirNNbXmNvirTbZCef6yqMGyai6xdVT6t",
        "4VgmX8MqJ9FQDey3bc6ZETTVaBqhNgoMZ82GyTEigSE6",
        "8R5XGievaDp9uXhZda7LjMBbpEWmtaJxzZ6wSNLU6Bg6",
        "BcpZT3rrW5MpZjh2epBACiDeWB4nz9bihxposjrkGbNq",
        "GnAXfSWE9CmJZkDHfzALB5DTr1JsqBA3TgvnUB6TSkpU",
      ],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "梗币玩转中华猫！",
      min: 1,
      max: 2,
      time: "2024-04-10T15:30:00Z",
      totalRaised: 200,
      tele: "https://t.me/KatcoinChannel",
      tw: "https://twitter.com/katcoinx",
      web: "https://katc0in.me/",
    },
    {
      id: 13123332,
      table: "quack",
      name: "QUACK on sol",
      logo: quack,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Dracula Gamble",
          icon: dracula,
          link: "https://t.me/DraculaGamble",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to $Quack, the quacktastic memecoin that's making waves in the crypto world!",
      min: 1,
      max: 4,
      time: "2024-04-10T12:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/QUACKONSOLx",
      tw: "https://twitter.com/QUACKonsolX",
      web: "https://quackonsol.fun/",
    },
    {
      id: 13123332,
      table: "joebomeow",
      name: "Joe Bomeow",
      logo: joebomeow,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Weibo Gambles",
          icon: weibo,
          link: "https://t.me/WeiboGambles",
        },
        {
          name: "Wulfden",
          icon: wulf,
          link: "https://t.me/WulfdenX",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "where Joe Biden meets adorable cats in the world of cryptocurrency!!!",
      min: 1,
      max: 4,
      time: "2024-04-09T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/JoeBomeow",
      tw: "https://twitter.com/JoeBomeow",
      web: "https://bomeowsol.com/",
    },
    {
      id: 13123332,
      table: "pepebutpurple",
      name: "PEPE BUT PURPLE",
      logo: pepebutpurple,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "MUMU THE BULL",
          icon: mumu,
          link: "https://t.me/MumuCaller",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Where Pepe Goes Royal in Purple Hues!",
      min: 1,
      max: 4,
      time: "2024-04-08T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/PEPEBUTPURPLEchannel",
      tw: "https://twitter.com/PEPEBUTPURPLEX",
      web: "https://pepebutpurple.xyz/",
    },
    {
      id: 13123332,
      table: "toby",
      name: "toby",
      logo: toby,
      tag: ["Safu", "Audit", "KYC", "Doxx"],

      marketing: [
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Dracula Gamble",
          icon: dracula,
          link: "https://t.me/DraculaGamble",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Toby: Hoppin' into Solana, Ribbiting Returns Await!",
      min: 1,
      max: 4,
      time: "2024-04-08T12:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/tobyonsol",
      tw: "https://twitter.com/TobyonsolX",
      web: "https://tobyonsol.com/",
    },
    {
      id: 13123332,
      table: "benny",
      name: "benny",
      logo: benny,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Kong on Chain 🦍",
          icon: kingkong,
          link: "https://t.me/Kong_on_chain",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Making Waves in the Crypto Sea with benny!",
      min: 1,
      max: 4,
      time: "2024-04-05T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/BennyProject",
      tw: "https://twitter.com/BennyProjectX",
      web: "https://bennysol.xyz/",
    },
    {
      id: 13123332,
      table: "katpe",
      name: "KatPe",
      logo: katpe,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Merging Memes and Meows for Crypto Fun!",
      min: 1,
      max: 4,
      time: "2024-04-02T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/KatPesol",
      tw: "https://twitter.com/KatPe_X",
      web: "https://katpe.fun/",
    },
    {
      id: 13123332,
      table: "pengwifcat",
      name: "Pengwifcat",
      logo: pengwifcat,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Dracula Gamble",
          icon: dracula,
          link: "https://t.me/DraculaGamble",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Where Penguins & Cats Collide for Crypto Fun!",
      min: 1,
      max: 4,
      time: "2024-04-02T12:00:00Z",
      totalRaised: 150,
      tele: "https://t.me/pengwifcatchannel",
      tw: "https://twitter.com/Pengwifcat",
      web: "https://pengwifcat.fun/",
    },
    {
      id: 13123332,
      table: "kitcat",
      name: "Hello Kitcat",
      logo: kitcat,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Kong on Chain 🦍",
          icon: kingkong,
          link: "https://t.me/Kong_on_chain",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to Hello Kitcat, where charm inspires blockchain innovation! Join our adorable community as we explore the endless possibilities of Kitcat",
      min: 1,
      max: 4,
      time: "2024-04-01T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/HelloKitcatChannel",
      tw: "https://twitter.com/HelloKitcatX",
      web: "https://hellokitcat.xyz/",
    },
    {
      id: 13123332,
      table: "meow",
      name: "Meow",
      logo: meow,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Dracula Gamble",
          icon: dracula,
          link: "https://t.me/DraculaGamble",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to Meow, where the language of cats inspires blockchain innovation! Join our playful community as we explore the endless possibilities of feline-inspire",
      min: 1,
      max: 4,
      time: "2024-03-31T12:00:00Z",
      totalRaised: 150,
      tele: "https://t.me/MeowSolChannel",
      tw: "https://twitter.com/Meow_ProjectX",
      web: "https://meowsolana.me/",
    },
    {
      id: 13123332,
      table: "katking",
      name: "Kat King",
      logo: katking,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Kong on Chain 🦍",
          icon: kingkong,
          link: "https://t.me/Kong_on_chain",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to Kat King, where feline grace inspires blockchain innovation! Join our regal community as we pave the way for a more sophisticated future",
      min: 1,
      max: 4,
      time: "2024-03-30T16:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/KatKingcoinsol",
      tw: "https://twitter.com/Kat_KingX",
      web: "https://katking.xyz/",
    },
    {
      id: 13123332,
      table: "pella",
      name: "Pella",
      logo: pella,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to Pella, where community empowerment drives innovation in the blockchain world! Join our movement as we create a more inclusive",
      min: 1,
      max: 4,
      time: "2024-03-30T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/PellaChannel",
      tw: "https://twitter.com/Pella_Project",
      web: "https://pellaonsol.xyz/",
    },
    {
      id: 13123332,
      table: "xpidercat",
      name: "Xpidercat",
      logo: xpidercat,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Dracula Gamble",
          icon: dracula,
          link: "https://t.me/DraculaGamble",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to Xpidercat, where agility and curiosity drive innovation on the blockchain! Join our community of explorers as we push the boundaries",
      min: 1,
      max: 3,
      time: "2024-03-29T15:00:00Z",
      totalRaised: 150,
      tele: "https://t.me/XpidercatSolChannel",
      tw: "https://twitter.com/xpidercat",
      web: "https://xpidercat.fun/",
    },
    {
      id: 13123332,
      table: "lily",
      name: "Lily the Seal",
      logo: lily,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Kong on Chain 🦍",
          icon: kingkong,
          link: "https://t.me/Kong_on_chain",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to Lily the Seal, where grace inspires innovation on the blockchain! Join our community as we work together to protect the environment",
      min: 1,
      max: 4,
      time: "2024-03-28T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/LilytheSealSOL",
      tw: "https://twitter.com/LilytheSealX",
      web: "https://lilytheseal.xyz/",
    },
    {
      id: 13123332,
      table: "pepeg",
      name: "PEPE's Grandfather",
      logo: pepeg,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to PEPE's Grandfather, where tradition meets innovation on the blockchain! Join our community as we build a legacy that honors the wisdom",
      min: 1,
      max: 4,
      time: "2024-03-27T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/PEPEsGrandfatherChannel",
      tw: "https://twitter.com/PEPEGrandfather",
      web: "https://pepeoldsol.xyz/",
    },
    {
      id: 13123332,
      table: "bop",
      name: "BOP",
      logo: bop,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Dracula Gamble",
          icon: dracula,
          link: "https://t.me/DraculaGamble",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Bop: Where the Killer Shark Meets the Penguin Prey.",
      min: 1,
      max: 4,
      time: "2024-03-27T12:00:00Z",
      totalRaised: 200,
      tele: "https://t.me/BOPChannelSol",
      tw: "https://twitter.com/BOP_X_",
      web: "https://bophuntersol.xyz/",
    },
    {
      id: 13123332,
      table: "homer",
      name: "Homer Simpson",
      logo: homer,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Kong on Chain 🦍",
          icon: kingkong,
          link: "https://t.me/Kong_on_chain",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Get ready for a ride filled with 'D'oh!' moments and plenty of donuts",
      min: 1,
      max: 4,
      time: "2024-03-26T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/HomerSimpsonChannel",
      tw: "https://twitter.com/Homer_Simpson_P",
      web: "https://homersimpsononsol.xyz/",
    },
    {
      id: 13123332,
      table: "pome",
      name: "POME",
      logo: pome,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Buy POME will be rich!!!",
      min: 1,
      max: 4,
      time: "2024-03-25T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/POMExChannel",
      tw: "https://twitter.com/POME_SOLL",
      web: "https://pomeonsol.xyz/",
      contractPresale: "D7mz3wpF6LSZznGBj3gM15cmaNCtivMduajHbAqwJLa",
    },
    {
      id: 13123332,
      table: "anpe",
      name: "Anpe",
      logo: anpe,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to Anpe, where nature inspires blockchain innovation! Join us as we harmonize technology with the tranquility of the natural world",
      min: 1,
      max: 4,
      time: "2024-03-25T12:00:00Z",
      totalRaised: 200,
      tele: "https://t.me/AnpeChannel",
      tw: "https://twitter.com/Anpe_Project",
      web: "https://anpeonsol.xyz/",
      contractPresale: "39LfRMqRie7bz8qBQcqpAQ799X95MZvPT6qHrb8cth5V",
    },
    {
      id: 13123332,
      table: "catwifbag",
      name: "catwifbag",
      logo: catwifbag,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Kong on Chain 🦍",
          icon: kingkong,
          link: "https://t.me/Kong_on_chain",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Unlocking the purr-fect investment opportunity with CatWifBag Memecoin!",
      min: 1,
      max: 4,
      time: "2024-03-24T12:30:00Z",
      totalRaised: 100,
      tele: "https://t.me/catwifbagChannel",
      tw: "https://twitter.com/CatwifbagX",
      web: "https://catwifbag.xyz/",
      contractPresale: "3JiukkViHszZcbhMuFjLUwZLyv7CLJBeGtwvZfcxdJh4",
    },
    {
      id: 13123332,
      table: "mcdonald",
      name: "McDonald's",
      logo: mcdonald,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "If you’re not a risk taker, you should get the hell out of business.",
      min: 1,
      max: 4,
      time: "2024-03-23T14:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/McDonaldSolChannel",
      tw: "https://twitter.com/McDonaldProject",
      web: "https://mcdonaldonsol.xyz/",
      contractPresale: "8uNMoB21MwJ8JdKRxJEgGx9o6tN4PUdPaSWBndZaT4QP",
    },
    {
      id: 13123332,
      table: "cpctest",
      name: "CPC",
      logo: cpc,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "CPC Memecoin 是一个创新的加密货币项目，巧妙地将中国共产党的标志性形象融入其中。",
      min: 1,
      max: 4,
      time: "2024-03-22T15:00:00Z",
      totalRaised: 100,
      tele: "https://t.me/CPCChannell",
      tw: "https://twitter.com/CPCProject",
      web: "https://cpconsolana.xyz/",
      contractPresale: "7iayt7UG3S3rc2mKC8wZxkBt9MDZC4NGngRFH8SXfbhY",
    },
    {
      id: 13123332,
      table: "pengisking",
      name: "Peng is King",
      logo: pengisking,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to the world of 'Peng is King' – a unique memecoin project that adds a whimsical twist to the cryptocurrency landscape",
      min: 1,
      max: 4,
      time: "2024-03-21T15:00:00Z",
      totalRaised: 150,
      tele: "https://t.me/PengisKingChannel",
      tw: "https://twitter.com/PengisKing",
      web: "http://pengisking.xyz/",
      contractPresale: "3t2cJ1uqZypuuPAQp2gn7beVCs72fQqtm8QgVbi24pMh",
    },
    {
      id: 13123332,
      table: "smoly",
      name: "Smoly",
      logo: smoly,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      whitelists: [
        "ABkE3sn23UAzL8teRE41MYVq6KNPWzkX3Uj3rWtEGNFw",
        "7mqbMg3QKc7tbrLLAr6apSPATxGbrUqBih5hYEMGzHTi",
        "9v2VsEKSiGVGgn2Cs5et6RrW4J3iiN2PvM8T9r7baWVt",
        "7AjWBwToLvFWsX6VTGPdYhY5yczmo63G3c7iwYM8jxBS",
        "6u3qWsHfK7NxxQG1814Fq9JMVvcyTjpmfb9Zh2WWQYF4",
        "DwMVDnLQaTR2kU4nNnzwQ3iJbU1BLEYKbiP6tApaLTTU",
        "Db2EWVNFpeqDTUvwHSLxtP29pSjNQyDBKowS9SeUnqYp",
        "5vP9XdbGKU65QnXga3UQhA2Mn5puy7W59qTUDCQXmJwd",
        "CcmYrfxprDtzvcsu1T5M5gUHpqG1UnmbAFB6bQqhcb2J",
        "5JoMecXjYZtpqwFEMjZDkFCzTaU5fLoi2XWBL6sEpQS5",
        "4xw7k3JUnCuVoq6pFZZkmCzgRURtyMTCSCvpFkxNQGVp",
        "6ARDhdqTpU6cVhwrT8bxqA1SqBncFw1tNtAUa2EVvsDg",
        "3BymtcDP8MW2LBA2gy5hvzkGMneWHVEz8gdps6do1x9j",
        "HwQK8UFnpVJ1C4THMp3poSmrNHVmZd3ZhLg5gFArHkAe",
        "Gei93EhFT1uZo55Tf1ACMY7SUDRUfMFN5FX3VDBd1vcL",
        "9DvBZCGQdgGCRP4R231LMZQPGmg7khH3tox4szeTDhBv",
        "GYeiV7HU5G96eKXCvAET63iU3KY8bnRXnuwHy3bctSGh",
        "9qy7wn6LXFUMwsFBMQKgw8G7oGuMxkm5KFHuB6LFz2Yn",
        "3j2ctzJkcr4Ksv9gdYguHQ3Ci59oceRPyQd1whGR8dWJ",
        "3nD84yfFgN4SJnzwN841edTmGJTEz6Ho9vYJfTHT85am",
        "Gqsf8PG4aTB8fXo1cnLVN61egCwv4x4P2tC3tLgNZSx7",
        "2eiJ3CajidbXCH2JXEBmKQqZy44r4W5HsQRixLg7egLb",
        "GYeiV7HU5G96eKXCvAET63iU3KY8bnRXnuwHy3bctSGh",
        "4gAjhXtaWqc3hCJDYiMp2XZ1rQJjnHjZYTWoFusVbUoM",
        "4uNKW99a9jVnjegHvi1Wg5MWfahgZgBEwkLumYnidfMo",
        "1VUdqv6xFrEroAegD8pF1JXp9era3yd2buwTpWXTFoc",
        "2B2QwpRkonKsM19PjWCCkg5WmwLQyNJ7sgogFEuJ16tw",
        "5cYtrCPchfw8w7dFyd4ondxMwWFWQ163pWtvGKY1dD7G",
        "AAQVdxEuQhLfQbhx9JEa4FMHp8xpoGrtrCksVbM26yBF",
        "FQ5vra631FL24L9AHwodZKReKVETiV6RCbngjrCahDoN",
        "C2eWGWrcLRKpCg3jRfcZ5Z9HRHKHa27efuW87CQ9Yzf1",
        "BTp7S74z3Ff8CL3ezkiCy39SqLGnSu3n1DGcicztLmtq",
        "C6BAXF4FVE81EaoHTju2XDZLDPTXndToGNyfzM8ePhUg",
        "J9Qo9suaypwTuGrBYguG63nk4UBQkvv7wH4wh4yc55Gd",
        "Czm7NqLiaEvNkTnMvWmMpQL2vp6DrPWSQgXJdXqqSfJS",
        "88dVrLeL6cTn8pEciG98QSKADYvCiGRR4hMAGEqANkSz",
        "DtSLmoYVvgajW8RFoHWbDikhrHwGEAUtKbtX4uN2bN7d",
        "Fmho4UHMhxnm6z4fQFgf4fnHLMgWDzWRhkZrSUP6UutS",
        "G1KBc334ZiV2XD5GQmZtpVihGrG1n65W99aYtHvfuSfp",
        "4hzWkq9XMF5BRsLYTXW2mD6bFD2BWxoyjmh6WtdrEQbb",
        "FkqYWj1nBWYvzWmadTTGUSHw9Ljh147UjMbZaHjsRTbD",
        "EyafKJE4T9bGbSEDs1JTE76h9cQJwqJkxa5wqHmU6Cd6",
        "9My8eMVECRDjGqjJSEERY941HEbshvPjFQvcMbJfq3eR",
        "AF11Ygqg2VkiHAgYbeoHBm9QVJBCsZuwotgBaxhiUXJc",
        "HNtJcCkgXSw7xdXgJoYqPHnGJwyrAuFRm6heVwGjALoZ",
        "HTi9qvvoWpB8FTGeaLDJSAatZ7r5ESzRS7e63iwZ2n98",
        "HyAoVJE5NRyeRTjGdpx11DRNwuAuqmM34NgiMyhbcP4A",
        "FG8kEAt8B3y35Lvstu5cV4zHdKMy7i63KNYC2q7S2HGV",
        "9hon9vpwdUwM9VaYgJkXeMV7Rxoy9PqzG6i2QgCdjr5A",
        "6BV2Gqkk89xjCgWSVd24a1xjCHPJKpJnUzAvmyrcS9Zm",
        "Hc8fmpMXRFvz4VyaVSifnwx6LhGD6EZBqoTZDgXKY25F",
        "9XBxF9rydTc6p5f9bZ6qoj59p1LwjRHPF1qjPSRMK2Sz",
        "6DjbKKDpjL6GxqY3CdbzhMptzHYKhNG7yjz32iLrfaK5",
        "FCdGg8rdezHieUb5RmrdEG4AsbVKYSP4956QhksoA2fM",
        "BqThCwjKpPuqTjadeg7CnQLWbk8f6JsvdDrxwkwtCwjb",
        "EeknpgCEnDsjCsVUYy3PKT8TNcz3FCf35DQZNWavmAYn",
        "J2Zi26t2DpANfTBAfNNm1mLbjLGETAQDFiqXtpkt2MSS",
        "GRgSwxSaBwQbXQjwjhtqr6ne6XhoKor7iCe7qoiDPNTD",
        "78s8rwJmnZ75yQaMmMSAkkYL4D824H6vaBH7sqKvt8F9",
        "247qj1R8R15fN1hdaubcSrBMZNKzg7QH7yxi6NLCkxKS",
        "72ho18HjGRavJc81DjUNN6bdRADT2catx3bcTEXMQpaH",
        "4anVRRLdELQ5RhHaPHzc32LsBY2DUZNWqc6YjrLrvA8H",
        "8xBkZ2A9q1tLyLSNWuKuVDajbfEeLbJ5FFGtSCTMJ3EH",
        "9wbbLnxGdsGmxGiwbyNQFhPGHC6eM3b2NvFd8ZLfDVpg",
        "4Tz3YfsyJP5uqtzc3CjXTQLsg6ca68vR2Xtci4pXzMGE",
        "Cip7KCKt5ys9XbdEJo2uLNeCeVybKstWikDWHyZnYsY8",
        "EWthNqty5EAEzaNzv4rWyoZGtgRaFBDDSe5RGuRzwcqS",
        "2en3coGEEe8XkcSaP5PRTmiQ8BHfyoNVrRRKR1JNaumj",
        "EtUZgUbXxqpaCvkCXt6q8Tdd5MzB8eL2XhT5JfF66fEc",
        "7pb4vWKPxDs56gjkZWEC1NnjcwHSEF1EiSMPAMzbAQDL",
        "LSxMCZP9tqR2wBzWnhBd2hc9VYrfzKpknwQcZdR1kvw",
        "4jzsryJAkh8GwDqooT45wP13iY9h5gtt4EjE8Ejbsmhs",
        "9yaQY6dD3YhYULAZhVCNkxcxPtJbRUcMRo7MGwGJz8z7",
        "J9SqKvsRCaqGCAJyxnS32XQCjuzdefHaEQRTr7StMQ6u",
        "HJyk7qnZbC2ut725q9waooNoe1FS7tZbR5gZTsJNThZL",
        "BgceupnQZ7phARoRT35coNiRKrK5TCypU42SjE7HYAXi",
        "5GtdKd6M497GzZia9jXPv1qUq7ow6UvqUuM2tghLJGnP",
        "7ycUu3R9TF8HWr5pQqFVjWvd78KM6kcN9kUeQKvfp2nW",
        "Ht5xoAteCpqfpUTgajEARVB63tDEksa7MKp4j9jAzKEa",
        "69Dtp6hTbozka9vX6EK34hAW1PckZR9y3M1x9XP2xfAs",
        "2krMXGZbXw3ATig75U9HRVUYakXUNW9QBNT82ovZdK5r",
        "8jbP4HHtaKFNw54KNqXbDc1Av3xMrj8JzQkEDjwh4tEM",
        "AqatCHShJ1MG21AKjHF2aywErFJ8HzDzDmceg2nEvQWw",
        "7CnTSLm1ybVqdaTAzX8CQYafNWG3eqY2VHsGJgmKzmZw",
        "J5acSLpd4KxBJsbfL2AdQ21LusA9j4AfyPtV7DVDNCHo",
        "7pbX7Br3G3fNYiuJnhATkDZmA8w7QF4k6B2MefcdahuL",
        "J1G7RBxus56mXVLfTLtfCLEFuEbYKPPXaf1fqFc7tYLC",
        "Bkrn9ncYBLRMsTCg5P793vo3C9Tm8EYXXLppdmunyAv9",
        "JEFXq6SyLomno7uXZGRBTdSBNAJh19uv3FoF3o596aYq",
        "2ox3XtMCc9k93MyNo6f6ibCfgAM3YZBMs85AeQrYFgeN",
        "EU67NyQhc6ASynSYoTwrbnja5QeoYsy5hYYjDWx9C4Li",
        "2zKnBovBZckBhiU7Yc8uQpShCA42aTyrWuVCVDwYkzZu",
        "2Kw6Z4kU9Dppg6eYHL3oGi7WAod2pisvoe8DKq6CtygK",
        "GFbYwuSAgK5g5BfVVb4pr6DgsXbcruVvNjHh8BusNpFm",
        "6xtH5qzfpc17MLA2SEnyiq5WhyHS3EVKBwLJYd3ijQ5S",
        "E75jnaeKfsqQDsKn9mzv7jaB7mFs3PmaeA3FAgVhykHu",
        "HiM8ygM9BcemUmYfKDp2sGjbb3nRkJzxoZEQVtEuNRMt",
        "FxLredJrw9frRYTidDX6JjQkvrzQubcdEgnnuyJGeczX",
        "Fb1Tsce8WUsSdwhtBqCe5fF5A6DhMq6rJcNcrgtD4ygy",
        "GKxZKEVsHUQdovUe2pC3Es58pJcMsTfZtARzyJXug7Dh",
        "4MeXmKXDT1wh9Z9rb5GjauTRbCnwFJmorCws4y3way1o",
        "APDZggSBB6SfFADm5TkNGYWkukhoisfz1FRuqMRphq9x",
        "65gkJBGF5iWLrf94qzqVnZtXiCMirZwpebuawWEG6912",
        "5Fi2ogsTWMZUxGcH8pHXrvZkc5UrHAtZKqoXKjohXjUg",
        "5iMLQptghMRZc2ye1iT8rhHdJs3TdxK5SqCrvgwY7WxY",
        "h9gUFXAWHEhV6m2KJ8F528gGfMPwzCvTFNfRpE6t5nr",
        "ETLjDKDaQbQem2D8z64TkUdj8KyLhdffRGfwmxhkL5FJ",
        "Gdj4D2Spx6fHcHtCunY7bTKjz5RWGEkSTywmVjLTcG4c",
        "NMDo1Mfgj8KVXCadPJaxpdFV7Yz6pQ9cRV71BqSmuca",
        "A1ER5GWwRcC6iFHMwiJBAk6EXFvhEa64FQ6uPbNgNSHB",
        "5W3xtfpqu7VnkWKbpwM7dJNJKxiifgwTp9y2atJfFZMH",
        "DhK2BgbfKivh3dFdtukDMTuagaPLxAiYX17jg9ZFNk1u",
        "4eLj3HuFRUy2oyCL4B1tYmN9bFtxetNhwyWT148ZQqZP",
        "CZc6oovBTgpgfwJueMQJ7rug44UrZHTET7wkq1bGbUVc",
        "3kjiJ45ovi1bVKAESRoFqCJ7E7goveaprQBXBVzXgd3X",
        "HFvM1cnMaa346YpSPnqmoFLvRQfqTrpM8KA5CcJ4zaup",
        "AxhHDCqdp34qgMKnkgpff2VxafezdTatkidd4ErDnVbp",
        "EXwxvvo5so6TVRAQHf2UrBPSc2aMg9xwm7nys1RYc9Wj",
        "CYsULgq4J6Vh5LpZJRpukZE5g6pczbBj73bkx7uJhQY9",
        "5sRhDjaunrRTha8tqEBQorQuMsr6DqneKGshnAeFcnZG",
        "8Zo2mphBA1QiPD9DBD3MGD6QDS8hA6iP9epSntx63Ghj",
        "qb1kCw54dT4kmux79G7NTPJ8qPn8jZLmWkVcaps4FjT",
        "6RGL6yK12bkZw5CFpCZRULTnyCB551g7PMkkbp6uCQQd",
        "Eo1zSCCfFHPm2v5TyUkcLChHFrLvqziurjQWTGkusGBE",
        "BED8jYpDzqBJ2DbVTJy1S2U9TL9SxtTpGaqLoNm8oNmj",
        "29bjzWX1ihtWv89gQKWdnoFcVi2FTWeVeecqZ8EdWFgW",
      ],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Smoly brings charm and excitement to the crypto scene",
      min: 1,
      max: 2,
      time: "2024-03-20T15:00:00Z",
      totalRaised: 250,
      tele: "https://t.me/SmolyChannel",
      tw: "",
      web: "http://smolyonsol.xyz/",
      contractPresale: "3U7WVgWL1aURjdmJ273ehkTZnDEewVojeRs9Vng7G1UJ",
    },
    {
      id: 13123332,
      table: "fineandsmole",
      name: "FINE and Smole",
      logo: fineandsmole,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "This is FINE",
      min: 1,
      max: 4,
      time: "2024-03-20T14:00:00Z",
      totalRaised: 150,
      tele: "https://t.me/FINEandSmoleChannel",
      tw: "",
      web: "https://fineandsmole.xyz/",
      contractPresale: "EefJtqjNZRRf8LzFNSpRW76Xxo3t3DQL4shcaaBhaaQD",
    },
    {
      id: 13123332,
      table: "anapple",
      name: "An Apple",
      logo: anapple,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "An Apple is a wonderful thing",
      min: 1,
      max: 4,
      time: "2024-03-19T15:00:00Z",
      totalRaised: 150,
      tele: "https://t.me/AnAppleChannel",
      tw: "https://twitter.com/An_AppleX",
      web: "https://appleonsol.xyz/",
      contractPresale: "G9sJ8aXSbzhYqwau8zzjQXHeVwLThoY4Rtj3ujEJ1KQi",
    },
    {
      id: 13123332,
      table: "snappe",
      name: "SNAPPE",
      logo: snappe,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "SNAPPE is the best memecoin on Solana",
      min: 1,
      max: 4,
      time: "2024-03-18T15:20:00Z",
      totalRaised: 150,
      tele: "https://t.me/SNAPPECHANNEL",
      tw: "https://twitter.com/SNAPPE_",
      web: "https://snappe.tech/",
      contractPresale: "Ga4iEBvGazbVrve497h3YWq38pU32rrQr8U7VDyp76oB",
    },
    {
      id: 13123332,
      table: "sulana",
      name: "KING OF MEMEs",
      logo: kingmeme,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "SULANA is coming on SOLANA!!!",
      min: 1,
      max: 4,
      time: "2024-03-17T15:30:00Z",
      totalRaised: 200,
      tele: "https://t.me/KingOfMemesChannel",
      tw: "https://twitter.com/KING_OF_MEMEsX",
      web: "https://kingofmemes.net/",
      contractPresale: "2Y3UR8yCgWPkjojc1cevRy2ZXURFjYjGF4BsuJHgQ3a9",
    },
    {
      id: 13123332,
      table: "bookofdoge",
      name: "BOOK OF DOGE",
      logo: bookofdoge,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "History of Dogecoin",
      min: 1,
      max: 4,
      time: "2024-03-16T13:45:00Z",
      totalRaised: 200,
      tele: "https://t.me/BOOKOFDOGEChannel",
      tw: "https://twitter.com/BOOKOFDOGEX",
      web: "https://bookdogsol.xyz/",
      contractPresale: "XkAhK5kVpX2v4uZiyynwPsxYdxhvMXF1HqkXTakTgCf",
    },
    {
      id: 13123332,
      table: "renaldewifhat",
      name: "Renaldewifhat",
      logo: renaldewifhat,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Siuuuuu!!!",
      min: 1,
      max: 4,
      time: "2024-03-15T15:00:00Z",
      totalRaised: 200,
      tele: "https://t.me/renaldewifhat",
      tw: "https://twitter.com/Renaldewifhat",
      web: "https://renaldewifhat.fun/",
      contractPresale: "HB3WxaexzWpR3tHQW1zsg45dE7YNZxsSt9P676yDw7mb",
    },
    {
      id: 13123332,
      table: "pekachu",
      name: "Pekachu",
      logo: pekachu,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Pepe + Pikachu = Pekachu!!!",
      min: 1,
      max: 4,
      time: "2024-03-11T13:00:00Z",
      totalRaised: 200,
      tele: "https://t.me/Pekachuchannel",
      tw: "https://twitter.com/PekachuXX",
      web: "https://pekachusol.com/",
      contractPresale: "Dqv3RWFugbupmBArUEVWd8j78gGCeHu1uhfBfSBcHjf1",
    },
    {
      id: 13123332,
      table: "shinhan",
      name: "Shinhan",
      logo: shinhan,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Tien Shinhan, often referred to simply as Tien, is a prominent character in the Dragon Ball series created by Akira Toriyama",
      min: 1,
      max: 4,
      time: "2024-03-08T15:00:00Z",
      totalRaised: 300,
      tele: "https://t.me/Shinhan_X",
      tw: "https://twitter.com/Shinhan_X",
      web: "http://shinhansoltoken.com/",
      contractPresale: "BZRdtLGcoW48ceVW151KxW3wzADSymkteebvSrYP5Mnm",
    },
    {
      id: 13123332,
      table: "pengwifhat",
      name: "Pengwifhat",
      logo: pengwifhat,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "HI, I'M $PENGWIFHAT!",
      min: 1,
      max: 4,
      time: "2024-03-07T15:00:00Z",
      totalRaised: 300,
      tele: "https://t.me/PengwifhatX",
      tw: "https://twitter.com/PengwifhatX",
      web: "https://pengwifhatsol.xyz/",
      contractPresale: "Dy5bkpxCmFbxtg5tcEBjLtAXkWqhAMtgHG9wTLyp1Rg6",
    },
    {
      id: 13123332,
      table: "supertromp",
      name: "Super Tromp",
      logo: tromp,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "$tromp own onli tromp nd be happy",
      min: 1,
      max: 4,
      time: "2024-03-06T15:00:00Z",
      totalRaised: 300,
      tele: "https://t.me/supertromp",
      tw: "https://twitter.com/SuperTrompST",
      web: "https://tromponsols.com/",
      contractPresale: "9VURJAQtZaa2BkGCme7xxVnkCZkkvjZiDLtpLqq9gRpZ",
    },
    {
      id: 13123332,
      table: "akita",
      name: "Putin's Dog",
      logo: akita,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "We bring innovation and confidence to you, ​join our community and let's make the new Akita Putin’s Dog on Solana!",
      min: 1,
      max: 4,
      time: "2024-03-05T15:00:00Z",
      totalRaised: 300,
      tele: "https://t.me/Putins_DogX",
      tw: "https://twitter.com/Putins_DogX",
      web: "https://putinsdogakita.com/",
      contractPresale: "GgWw6ZaszS4D1fNm3jCYF5UtBu2rxraUywPjYpazQHiF",
    },
    {
      id: 1001,
      table: "moby",
      name: "MobyToken on Sol",
      logo: moby,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      whitelists: [
        "7iAbHb5bBfUWDpjEr5B6r7VdN7QJQ52L1qsaY2huoM9y",
        "5f5ofYkLQ5QGMdBJiZQrFEn4GzUC77od9g3jHr8pXocg",
        "5pcyxKQBncrEPf982mD9dncChLEtuwzZsgoZxobZsvBt",
        "BcpTqx8Dx9cq4tiaSgVsjGk1MyWmKzogucLM8hXvtWAe",
        "AHQ1bqpHpzmMNzfh49BFk6WdkSG8XRRjZ7ysA7xGzxu5",
        "BDAPWqZq8ngGqxGczqQ4J4qqrgtJdRJH8HJFj931SEY9",
        "ESfzgPmqfLsz7VtbCVZQ3edTKxjgWEyARjnuNFdDRHtd",
        "G7uLoWrYQAgBJa96sscv4yfohuHsZ49waaEHxg7czBXZ",
        "35tr4wiczyC8uZR1cbX5t7sLVJLBQbJxgCBVHRZY8fhs",
        "HwQK8UFnpVJ1C4THMp3poSmrNHVmZd3ZhLg5gFArHkAe",
        "myvEVBsqtWYEXaWkmqzyH9ZmaroKPHMx6rfGV8orpub",
        "Bd1Q3vMiCnkrAkTtmeA4egwRq1v2xkKWdXFVRmZiunFJ",
        "2XY2Nk3LpqVUCLWkqafaaCLcyhr6cEBttyEMj2X2aV8Z",
        "2k7uYKcCLsEqXvW94XoWyK1dgig7bY7cWnCcueqocATs",
        "6WhB63np6g19esTvi4qZf34MBB1G8tLxKv9A1RbZgYjU",
        "GaEtRXnDjP3SLo8jaFkomTp44Y3umcjbzMmkYEyZknmA",
        "5cJ2NmhTzRRiMvNKbvNjAfrfi8HKKcvvde3S2M4iY6U8",
        "5a6KhEAWZJvwnVEcgiJMUSPYFd7eR6KsvrXa9RfHnRKx",
        "GhWGDWfgnmFRZGNSZkBJVtsQYBrsnNhVa3KVcWRY9DVB",
        "46anwBMHbhM5PwtutoQ1T6aT3xEEDFK3qaDZ4kpw4w2Y",
        "GPWireGmiLoBCALFZKKTkPhQk8G4PxD5eqkyfSfn8mwd",
        "9iuqYhJRs5pvjp1C1RYaS3q1AFeJybfk71xMmyjZWt4i",
        "BxYBAMonUk9PbsK6xeKF3hhFJh5VKfdUmof444XrdPCC",
        "8dgbbJVwvus1fgem9vbu1EyHCGWhmyLGvpFZbYaeX9nc",
        "BkhsFyhse9WXN6d4Gz8dxxVMgazeM83nGi1LxT9XmLv6",
        "DWYyMuynbrAssa2dv9C9LDpMuWBFNe8UsHuR89L78FLk",
        "BYa3Q9rZZC5ygWkTyvibWXQjZArVQo4x5rwVgRSxtsGj",
        "3wvECvY7CBrdXAYR7Fj1mtizr1g96KzbK4Ee7cAgHvV4",
        "CqM55e5fpwyaFvF2pG7VRkaoGMf3siHQjXBpBLesGywS",
        "9qhZHWruU5mD8ngGzgmRccZrdum8Fxcv5w6TdUEfjEDQ",
        "Crpcc6cHmNKJFrV19vAzb4N6SCkLmMrm7vPSdLLJTWYf",
        "DKY8Ls15D5yZutPi3rnqvonEi3pWF9miP91KuP5F9eAf",
        "CsKuRZXZN1dmJBvZxvXEevCZhoKo83Z7JwGcLyzyvPNs",
        "7Uob14F2Huwfr5J5o1XpHhjKxstiggH5fXnM2uGYP3vm",
        "DH6QF1VGZxxncsTLHLNmsCBVZ2SQVzXVajS1uyeCVzSu",
        "FtkYNzgpWFoTFySGHTXqCNcvz6c2W5TD2w8DesxdJqrT",
        "8hWZ61NfMnKvCA4KC9KBUiFQRjMBwm1VpGsPiuJrFQCy",
        "DCuD2Yt4Gu6yPbJnihbXEwZWAiCua9Da12MngnhRxMwA",
        "GiGAbwpF5R1NE2dnPANrLo7JB7aFAfmhqFqLZrtap8eb",
        "5Da6vSRZBJh9CFHCsx65CKi9yTwcoY8xCr9TKSTfRFzG",
        "12jog5TjtweoPZA2rbBbRN9LjRk9FuxMYKjrPvAuzraM",
        "BgLrFpontCRRWKeqCCAPwhpPzTxg7KLCYQTYU2s24aM5",
        "6tY5ht1R7A9su8mQetznx9R467AFzHCevmr74pW4edFr",
        "71cCAqRmRR1ixgmdJC5inTPbyf8wCxQCGvQKa9zqRzoB",
        "GfkD1x4PNFNAxT3vW1r91GGwy6a92YDqK2v4KdQXM8nh",
        "r19ztdsgvNX3Y2ZS7zQBhaBziuRWY2t3eWSX1Cu4T1X",
        "6Vgd2eP34k5poMNDQVhUXiLmrpRXtwvgMkdPpKC8B3C1",
        "sKsJx3bbfAsuF9yy7v8o6cdwi7ndhJxLe6hD69roBgH",
        "fybLFYzJnjNuV8VmTGoiuFypFycssnVVHS3ce1kAoBP",
        "iYFdP9HaTxJxW6KA6DdXVRbLTa6GruPSSaZie5JZybj",
        "GnRr6tkz1KJQQh1dk1wde1q1VZQ7yKMZmyjooe5oqyzm",
        "93Ub4szkjGGqaXY1mEbqG5hH8R48GpdvLEQKeq8juFLP",
        "GGYzfA87s3Xi1d6j23BPgzcJM2E6Tw4SUVbnQnF5VLyA",
        "5YdjD9h9KfzoQ1H2oBGtiJQ9wYGx6qhnDZyKxED86TF2",
        "4NiMtHSP1jJZiVonShPJbsXi6UnhrP9YQZSefANPfoKu",
        "Fv4iuSTaEwDVDBF6SYmzrHpnADLUvsG3BcWdHXuc35QP",
        "9DGKSeZT2XDZvyfQEHKFtkt9ws5MFRS9SFpJN32RJniE",
        "3HEkp32Kn5yF1CUuuooCRgEwK5vdV2Sph6sEDNUqnjid",
        "HvuyALyxsGMBh9LevTRoJytCuMupe7BijHzzFDqmXpci",
        "9XSLort3zVHdcMssbN4UtocCgruEikd8pYc8zRPwHCKR",
        "AM6uoydiaEXGgD4Z9VbaoLEfY4YdksSLKEMDYckKVUkw",
        "AvMY6XfAKmLbR3CAtkmW2yHfk6rFzmriVEPUx8NNwcC6",
        "HxqeftgrcyqAf2SmDhBpcXr4ABTGE9NCnA2mheKNxFEe",
        "qcsFgmhPZFUtVVVAGqjuN2z4b6HmpecE9LrM68vmF4S",
        "KHDNdfSU14E2zscmF99XkUrEbCoG36z29hE82bYrK5M",
        "87wr6TisJxek8zFQQhkcS1HzfsxjCzxjmu5zSCiAj7zo",
        "CkURbHPZgs5C2XcsNjmmVNQkCYRVXatvJCFnAHaFox1n",
        "578DznJpYrgnK17gB3Z4UT822enFHLQApSChXudN63Tm",
        "E7XNp97D8kqwSHm45z2kk3pnYLR2xn3dnBs6cU9CbLuZ",
        "C2TztFm2QAA9feNw9mgAFWxpD5ZsFXZzMtFykqn45L1",
        "66Xk1s4X8VQ3QJpwoqt2DogV3BSin8rVYPaLYLEziLFz",
        "9VLdZ65M38Ydcwrsy6nt6sCEovbEb6iCNWSdCpiFhvpL",
        "HJr2i46vuoMZ1VtvEtVyFAcr7Vk1wnrcqN6sJvKrDYCA",
        "2wGRcxVKtVLV6QMGRJyq61cqVGyFMXKYecd88k9yhTbS",
        "E7yqRsmQVaXYzTpNFcXurubKccixUJmJYfe4NMjL2q3s",
        "6FP2trDsK66zKcFhSDoH4FDjfzGWvHTnuExNx4pn6Wsb",
        "EFspSeai7Yy5ys8fDxNqJ9rRxcFF7yo7aTz98ZgQYWEE",
        "JDuAV8kVBtkyQfMCm5XQBcsa6mbega2U5sgKm8NuXRBM",
        "N5Mh91r5qkAGWymvdnTdgJ6iYSiZhwRAEdGqW6mGrST",
        "EMbkioVRDiwtdM6BH6UMeu92zyhVRN6smUe26ZbAkxMq",
        "55QBTQbJyGbWy2JAxMmddQ29E7P1Egp1oJL5rRSSJzZa",
        "Ebc5qdqpVtrhkcz6vhZq5mkKvBM7xuHvLh3zQmaWv1VR",
        "47TAcFCJVVrZH16KyrZP1aYtUFxDNz9fycfdkA2Kza2g",
        "3PTh9SddoucUX1GaaBDN4EKQPPzcvaH4hfPM4mSmCfMw",
        "4FoZHPvAFgEFsJ4sHgQzrnj5PUbTDz6sNmHE3ZVnFnEt",
        "Ghfg1o4nsSammPfueizj5noVmEex1T77H1ZUAKhUmUcw",
        "7Sz6EdB43Ey87UeWMqxa7XiPTzRBHmYWgKFrggeVHmwp",
        "6AD3vEVgWbRDszxkJFFmxuNiErHFgxBMky8p4k5M94wb",
        "Fe71MXe8xQdSKMUWycWDqWprVzAv6GTux28JaiZwSAAE",
        "52mXkaugkay7Cg9bqPK6gSXjr5zqR9ptvMV6i53LgiW7",
        "BqvR1k5YZsFbsnXSk44Nh7RjWaBMtMt9jaXmvhadQ4BY",
        "BapbYynmYpt1Beptv1yNmr4Fgz9M8vZoyVJwZEHaDuew",
        "FNKdSuC1QNrkRdPwqx1c5eTr5PUpxqE6sXgXkzxDBPKb",
        "Gz6SjUVinHRFnCuFV9z9eqtvJr5c6nMcXbkYS6C4TDj",
        "5GmsNqFi3epwPemtM1frfTTwQotsReSAVatpEWpz3KGj",
        "Ftz7rcDXqA268bPooZqpMT5m5T36WbNjdyF985UpwQju",
        "4X64kLKkVKGkAJHApawe1MHUo8WvNygwxZKQyqxb6fus",
        "5fDPdo5J3iLCBSLsPw7yjRNgTRD8aeJRX3oMeXAr3sXG",
        "HbeUZG3KJCzMaTu399h6NQkmHqqkK3tVDmcuYGYo7eXt",
        "8pEKDnKCJocY2S2oorxh6cq2cv3wp1LALdhCWZCgHon5",
      ],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Moby emerges as a visionary platform in this turbulent landscape, with a mission to redefine the ICO paradigm.",
      min: 1,
      max: 3,
      time: "2024-02-23T12:30:00Z",
      totalRaised: 100000,
      tele: "https://t.me/MobyOnSol",
      tw: "https://twitter.com/MobyOnSol",
      web: "https://launchmobysol.xyz/",
      contractPresale: "4dxv35rJ2KES6RVnKBqqqmNpPapVEFwdQVx1HkfkTKcZ",
    },
  ];
  const [dataTemp, dispatch] = useReducer(dataReducer, initialDataTemp);

  return (
    <DataContext.Provider value={{ dataTemp, dispatch }}>
      {children}
    </DataContext.Provider>
  );
};

export const useDataContext = () => {
  const context = useContext(DataContext);
  if (!context) {
    throw new Error("useDataContext must be used within a DataProvider");
  }
  return context;
};
