import React, { createContext, useContext, useReducer } from "react";
import meme from "./images/meme.png";
import babycaller from "./images/babycaller.jpg";

import mastercat from "./images/mastercat.jpg";
import theone from "./images/theone.jpg";
import dracula from "./images/dracula.jpg";
import mumu from "./images/mumu.jpg";
import wulf from "./images/wulf.jpg";
import weibo from "./images/weibo.jpg";
import MM from "./images/MM.jpg";
import whitePlusIcon from "./images/icons/white-plus-icon-3.png";

import rcat from "./images/rcat.png";
import bebe from "./images/bebe.png";
import jiffpom from "./images/jiffpom.png";
import nala from "./images/nala.png";
import pppproject20 from "./images/pppproject20.png";
import hippo from "./images/hippo.png";
import wdog from "./images/wdog.png";
import bit from "./images/bit.png";
import flavian from "./images/flavian.png";
import akira from "./images/akira.png";
import wojakai from "./images/wojakai.png";
import ayane from "./images/ayane.png";
import dogwifmagnet from "./images/dogwifmagnet.png";
import doddy from "./images/doddy.png";
import satoshielon from "./images/satoshielon.png";
import diddy from "./images/diddy.png";
import fwiga from "./images/fwiga.png";
import maya from "./images/maya.png";
import esti from "./images/esti.png";
import scd from "./images/scd.png";
import mooman from "./images/mooman.png";
import muudeng from "./images/muudeng.png";
import poplly from "./images/poplly.png";
import wdeng from "./images/wdeng.png";
import fwaga from "./images/fwaga.png";
import wiftrade from "./images/wiftrade.jpg";
import leezeng from "./images/leezeng.png";
import popdeng from "./images/popdeng.png";
import catgo from "./images/catgo.png";
import misha from "./images/misha.png";

import panda from "./images/panda.jpg";
import kingkong from "./images/kingkong.jpg";
import vsb from "./images/vsb.jpg";
import travel from "./images/travel.jpg";
import { dataReducer } from "./reducers";

const DataContext = createContext();

export const DataProvider = ({ children }) => {
  const initialDataTemp = {
    rpc: "https://rpc.ironforge.network/mainnet?apiKey=01J218BG40T275QV1QW9KJSSK9",
    listPresale: [
      // {
      //   id: 13123331232,
      //   table: "pppproject20",
      //   name: "Project #20",
      //   logo: pppproject20,
      //   whitelistsShow: false,
      //   tag: ["Safu", "Audit", "KYC", "Doxx"],
      //   marketing: [
      //     {
      //       name: "The One Signal",
      //       icon: theone,
      //       link: "https://t.me/theone_signal",
      //     },
      //     {
      //       name: "Kong on Chain 🦍",
      //       icon: kingkong,
      //       link: "https://t.me/Kong_on_chain",
      //     },
      //     {
      //       name: "MemeX9999 | Gamble 🎲",
      //       icon: meme,
      //       link: "https://t.me/memex9999gamble",
      //     },
      //     {
      //       name: "Panda Caller 🐼",
      //       icon: panda,
      //       link: "https://t.me/Panda_X1000",
      //     },
      //     {
      //       name: "MUMU THE BULL",
      //       icon: mumu,
      //       link: "https://t.me/MumuCaller",
      //     },
      //     {
      //       name: "Add more",
      //       icon: whitePlusIcon,
      //       link: "https://docs.idosol.me/2.-unique-features",
      //     },
      //   ],
      //   des: "Ride the wave of innovation with Memecoin, part of the exciting Project #20.",
      //   ido: 1,
      //   time: "2024-10-26T15:00:00Z",
      //   totalRaised: 10000,
      //   tele: "",
      //   tw: "",
      //   web: "",
      // },
      {
        id: 13123331232,
        table: "pppproject19",
        name: "MOODENG MAXIMUS",
        logo: hippo,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "The One Signal",
            icon: theone,
            link: "https://t.me/theone_signal",
          },
          {
            name: "Kong on Chain 🦍",
            icon: kingkong,
            link: "https://t.me/Kong_on_chain",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Panda Caller 🐼",
            icon: panda,
            link: "https://t.me/Panda_X1000",
          },
          {
            name: "MUMU THE BULL",
            icon: mumu,
            link: "https://t.me/MumuCaller",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "MOODENG MAXIMUS will fulfill the prophecies of the ancient memeers",
        ido: 1,
        time: "2024-10-25T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/MOODENGMAXIMUS",
        tw: "https://x.com/MoodengMaximus",
        web: "https://mmtoken.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject18",
        name: "wDOG Terminal",
        logo: wdog,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Memex9999",
            icon: meme,
            link: "https://t.me/memex9999call",
          },
          {
            name: "💸 Money Maker 💸",
            icon: MM,
            link: "https://t.me/Money_MakerMM",
          },
          {
            name: "Master Cat",
            icon: mastercat,
            link: "https://t.me/MasterCat_X",
          },
          {
            name: "Dracula Gamble",
            icon: dracula,
            link: "https://t.me/DraculaGamble",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "An AI dog from the Truth Terminal. All AI tech is in this dog.",
        ido: 1,
        time: "2024-10-24T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/wDOGTerminalPortal",
        tw: "https://x.com/TerminalAIDOG",
        web: "https://wdogterminal.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject17",
        name: "Billy In Terminal",
        logo: bit,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Wulfden",
            icon: wulf,
            link: "https://t.me/WulfdenX",
          },
          {
            name: "BABY CALLER 👑",
            icon: babycaller,
            link: "https://t.me/BabieCaller",
          },
          {
            name: "Weibo Gambles",
            icon: weibo,
            link: "https://t.me/WeiboGambles",
          },
          {
            name: "Travel Caller",
            icon: travel,
            link: "https://t.me/TV_CALLS",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "ENTER THE CODE, UNLOCK ETERNAL LEWD WISDOM WITH BILLY NOW",
        ido: 1,
        time: "2024-10-23T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/BillyInTerminal",
        tw: "https://x.com/BillyInTerminal",
        web: "https://bittoken.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject16",
        name: "Flávian Is Online",
        logo: flavian,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "The One Signal",
            icon: theone,
            link: "https://t.me/theone_signal",
          },
          {
            name: "Kong on Chain 🦍",
            icon: kingkong,
            link: "https://t.me/Kong_on_chain",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Panda Caller 🐼",
            icon: panda,
            link: "https://t.me/Panda_X1000",
          },
          {
            name: "MUMU THE BULL",
            icon: mumu,
            link: "https://t.me/MumuCaller",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "You're in lost, let me help you.",
        ido: 1,
        time: "2024-10-22T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/FlavianIsOnline",
        tw: "https://x.com/OnlineFlavian",
        web: "https://flaviantoken.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject15",
        name: "Akira",
        logo: akira,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Memex9999",
            icon: meme,
            link: "https://t.me/memex9999call",
          },
          {
            name: "💸 Money Maker 💸",
            icon: MM,
            link: "https://t.me/Money_MakerMM",
          },
          {
            name: "Master Cat",
            icon: mastercat,
            link: "https://t.me/MasterCat_X",
          },
          {
            name: "Dracula Gamble",
            icon: dracula,
            link: "https://t.me/DraculaGamble",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "Artificial Intelligence Dog named Akira and we all are ready for this meta on Solana",
        ido: 1,
        time: "2024-10-21T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/AkiraOnSolPortal",
        tw: "https://x.com/TheAkiraAIDog",
        web: "https://akirasolana.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject14",
        name: "WOJAK Maximus",
        logo: wojakai,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Wulfden",
            icon: wulf,
            link: "https://t.me/WulfdenX",
          },
          {
            name: "BABY CALLER 👑",
            icon: babycaller,
            link: "https://t.me/BabieCaller",
          },
          {
            name: "Weibo Gambles",
            icon: weibo,
            link: "https://t.me/WeiboGambles",
          },
          {
            name: "Travel Caller",
            icon: travel,
            link: "https://t.me/TV_CALLS",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "WOJAK an AI project and ready for the new revolution on Solami chain",
        ido: 1,
        time: "2024-10-14T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/WOJAKMaximus",
        tw: "https://x.com/WojakMaxiSolami",
        web: "https://wojakmaximus.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject13",
        name: "Ayane",
        logo: ayane,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "The One Signal",
            icon: theone,
            link: "https://t.me/theone_signal",
          },
          {
            name: "Kong on Chain 🦍",
            icon: kingkong,
            link: "https://t.me/Kong_on_chain",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Panda Caller 🐼",
            icon: panda,
            link: "https://t.me/Panda_X1000",
          },
          {
            name: "MUMU THE BULL",
            icon: mumu,
            link: "https://t.me/MumuCaller",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "Ayane +6900% and this is the next stock project on solana",
        ido: 1,
        time: "2024-10-12T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/AyanePortal",
        tw: "https://x.com/Ayane69420",
        web: "https://ayanesolana.fun",
      },
      {
        id: 13123331232,
        table: "pppproject12",
        name: "dogwifmagnet",
        logo: dogwifmagnet,
        whitelistsShow: true,
        whitelists: [
          "Gbg3ZaUgBz69JPf3XWdE9C6pYA5TeggscHuxADPfzHDq",
          "CTXLqmpRjPSJape5VPRgjnL9azha6af8zERgN9ZZ1Mx6",
          "45V3HrTFguRx7Rct7vUcSZMwgZky2zgst1XNPXNak4iq",
          "8Kua6mqf2QSgDaCyQ2xJRbrvR1THzSVWb15rp4wwQ82s",
          "7G2eQiP4vWjNiwm4LYct3cJ2vhZKnwhdpbFfXKC2jE5y",
          "CY8GbshPNut62y3mEchBj6nHHiuRVXiLX7n5yAS6zm5J",
          "9FKPwLTxdkjYxkJyqP2vDS31uVkYDkoAaymsNMEb5Zcs",
          "FzWAYrKsS5iPpw61BYsaYn6mNhYkrNo8MLfyJYmjCugd",
          "EV5AskrivuUfdw9q7A2L2vQagh6Qw2SjvKLJVsX5DiGZ",
          "2e78B8DwjNH82YX3h9WRMUW3mgLdz69hEaG6Q7pJFVpe",
          "2uUowbMmZi1yyvL5n1y48GvR6ws7MW8T3CYpRfAxGcbN",
          "CWjBoJeMMV9BhBxnjVz7YgYuAFZktcJRdguerREeYrsa",
          "CTZ5XyPQsxGb5qdgFEGymqgSQ6BFNBMUD6Dh8ojLvK5r",
          "2sLKzAxuNbWshkAtmefqHccWxtvLdVJTM7pzRg5pBJKQ",
          "9FxD8QZ2B4YbcwaoXUKZYMTMz55n4jBYsJRZx8kp4xHE",
          "98iCJjgyGZnHcLkm6jR37XK9eE7GoJivs32mAPSj3ebE",
          "Cw6fvtZZNVJH5mPw9e1BypWVPbQ11MdTFuFShNL9jcgM",
          "FAdANfeonEH6NPRck8FkxyhC8bokvHR74FtBYeerryCU",
          "EH6z93hSvX9FCK8p81LdKZ8syyLhzFsr1nH6KwjTBw64",
          "F83L1SkpP97cbNY5pDDtjNJuy3F88jSxbQsHyrMLuyyU",
          "3GbAEqEtHEPEF1sizsqam9Ps1xwVRUmqzdZi41DkF7ux",
          "7dmwQ8SF3T2euUjzaEryMohNJLZAEFmCS1zz4HKeKCzu",
          "7JvfcyxJneLSgMVhueKV2Zj2gzbUquVKuR3yGdSTkD8S",
          "Xocs9SKnT9fScM7BhP22d7iJ9pKbKdQ3CjmF5dMZkx6",
          "5ckhD68VH7pTUMc4PWg5zbAo3yY2AvjxZ8Qtukh6c8jE",
          "7msXCoogutsVXhorwGjxViTi6rdxDn9Mk54RmCc5sr5W",
          "CKBc8S4mMTe8ke5SeTvbjEACg1A4pjeEzbE9tuaZHAHT",
          "8mNQwWB4yyg3YPSBtnjugAjSN5L2cr4A9a8YmmLxe8Ks",
          "GjemQFb4D9h6bSgo41vj6Gx3bVmRZeKzKugPcYHBZfs8",
          "CHEbYjneu5HDrFxHTiz8zLqfbcN3JgtebTCFAie7KGSJ",
        ],
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Wulfden",
            icon: wulf,
            link: "https://t.me/WulfdenX",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "Magnet is the only thing that pull up the market in these days",
        ido: 1,
        time: "2024-10-11T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/dogwifmagnet",
        tw: "https://x.com/DogWifMagnet",
        web: "https://dogwifmagnet.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject11",
        name: "Doddy",
        logo: doddy,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Memex9999",
            icon: meme,
            link: "https://t.me/memex9999call",
          },
          {
            name: "💸 Money Maker 💸",
            icon: MM,
            link: "https://t.me/Money_MakerMM",
          },
          {
            name: "Master Cat",
            icon: mastercat,
            link: "https://t.me/MasterCat_X",
          },
          {
            name: "Dracula Gamble",
            icon: dracula,
            link: "https://t.me/DraculaGamble",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "I'm your daddy, bring me Boden and Tremp. I will let them taste my Doddy oil!",
        ido: 1,
        time: "2024-10-10T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/DoddyPortal",
        tw: "https://x.com/YourDaddyDoddy",
        web: "https://doddytoken.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject10",
        name: "SATOSHI NAKAMOTO",
        logo: satoshielon,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "The One Signal",
            icon: theone,
            link: "https://t.me/theone_signal",
          },
          {
            name: "Kong on Chain 🦍",
            icon: kingkong,
            link: "https://t.me/Kong_on_chain",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Panda Caller 🐼",
            icon: panda,
            link: "https://t.me/Panda_X1000",
          },
          {
            name: "MUMU THE BULL",
            icon: mumu,
            link: "https://t.me/MumuCaller",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "Elon is the real Satoshi Nukumutu and you guys could not accept the truth",
        ido: 1,
        time: "2024-10-08T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/SatoshiNakaElon",
        tw: "https://x.com/SatoshiNakaElon",
        web: "https://satoshionsol.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject9",
        name: "DIDDY",
        logo: diddy,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Memex9999",
            icon: meme,
            link: "https://t.me/memex9999call",
          },
          {
            name: "💸 Money Maker 💸",
            icon: MM,
            link: "https://t.me/Money_MakerMM",
          },
          {
            name: "Master Cat",
            icon: mastercat,
            link: "https://t.me/MasterCat_X",
          },
          {
            name: "Dracula Gamble",
            icon: dracula,
            link: "https://t.me/DraculaGamble",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "I'm Diddy and ya are my son. Call me Daddy mfers!",
        ido: 1,
        time: "2024-10-07T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/DiddyIsYourDad",
        tw: "https://x.com/DiddyIsYourDad",
        web: "https://diddytoken.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject8",
        name: "FWIGA",
        logo: fwiga,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Wulfden",
            icon: wulf,
            link: "https://t.me/WulfdenX",
          },
          {
            name: "BABY CALLER 👑",
            icon: babycaller,
            link: "https://t.me/BabieCaller",
          },
          {
            name: "Weibo Gambles",
            icon: weibo,
            link: "https://t.me/WeiboGambles",
          },
          {
            name: "Travel Caller",
            icon: travel,
            link: "https://t.me/TV_CALLS",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "I'm the black frog on solana called Fwiga",
        ido: 1,
        time: "2024-10-06T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/BlackTheFrog",
        tw: "https://x.com/BlackTheFroggg",
        web: "https://fwigaonsol.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject7",
        name: "MAYA",
        logo: maya,
        whitelistsShow: true,
        whitelists: [
          "5t2RdSWfrEkJLxxLzjDNfJvVL5q22Aot2qGGsiYJUNCj",
          "FfjkbZu3145Avy5ZDhNDfirCMpZo6r2BGM6oojG3CtJb",
          "7FSmp26SXLrrkJfd9GwSUujYFpoqQMoS5DpncayBgnS4",
          "GwrxcDbzCP4kUXcHGrMhSDAoKycBJ3MpZXYcRw329VeN",
          "AXjTQCMkP37ZKkompt1wCzTBDs418KBDkEPM8EerucAp",
          "4V5FAYsjkTiGtTrsppfVeW3Wy9UwRnGSKwbfBy9BXjU7",
          "AoETqdYcEutjFWre416bEFTju5Q4vf5fXZWMFRnbpXvi",
          "nfu6Cj4UMa7VTPhX1LEFHazEaL9KkQVqe8xFe97jXzJ",
          "GG5dfPmqg2S5fdZoFSJJEaBrBQstLfhCchT9KR7mBGvp",
          "2WnkoMkuWWhXX3iCoyYYMLGCLdyxSgxdSVKUndCfD9Zf",
          "GYeiV7HU5G96eKXCvAET63iU3KY8bnRXnuwHy3bctSGh",
          "HBFkdgGc4oEypRS73j4in2AFQLYzXLnp3KY5NueJGhTZ",
          "HccXgTrBoHGw7mLFsGwWwqZn3rTUn9hqda4znZJr2y2J",
          "2JaCKKkx7gNBAa5ShdkQL44ir7CUzcvnaZR9uwnyU6aD",
          "CEjRGWYdCDpNhZzBrChjHwFx3EhgaML5fnfczyx7YKNo",
          "3rbiyabTe6L636mjgxGd5omKuBEMVoMZKQFmE7WSKp64",
          "4qctK526avi88Ud8d9yL8xd5fScX8Pbgo8CvV6ov4kGR",
          "2z8pWZay4AJpiTWCn5u3mVn2kqqwsdW93doRwBLvgwv2",
          "48aV7pLQxSsThvAU8BseXRAMK2UyWkgdoMbkgkKDYL5f",
          "7wLhiptfDfs4q4zDmRYkqV3sWKwntdzrLpQ8G4fqBJGx",
          "5aCsZJzssW926RQf39KGuWpdhSmHuYTWWEHCAuHy9yey",
          "C6Ypecr4sGr52RVhjPMrZECLTsVWqji4dqv5xssjEZsp",
          "2wBSQN8UL6Ndus8CCCscuuzqUkBZHwzN9uknARzSDRn7",
          "BYTiNDmDTbmLAWhWYf1BfjUbjoVrvNBPxBZjQdj5TFf4",
          "E7qaNfAXSt7NpwzY4ENvDqK451573zV6MkzoX3aPHcNf",
          "Euxi1i6NFbgWixzm1Go6u1BFwag3X347nEpwqoKwHjjy",
          "3UCTnSEFNrDEEkG7ZTTWHX2GggMWFatj8RE6KH2WC7eP",
          "R9KAoSPQXGCJJwcTmmsjeNdwjHZvrnL8eDXc6gZBHKm",
          "Bezdg2Geh4jGGTUemqPAJKx6qUa2LUJMzC1NJCQ8pUsi",
          "3tb8J6LrPXmjHeiQmXGKPRT65g7Bgo9BMspC7hEgY7eg",
        ],
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "WIFtrade",
            icon: wiftrade,
            link: "https://t.me/wiftrade",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "MAYA THE SAMOYED",
        ido: 1,
        time: "2024-10-04T12:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/Maya_Polar_Bear",
        tw: "https://x.com/MayaaPolarBear",
        web: "https://www.instagram.com/mayapolarbear/",
      },
      {
        id: 13123331232,
        table: "pppproject6",
        name: "Nala Cat",
        logo: nala,
        whitelistsShow: true,
        whitelists: [
          "6iYR6XJMR9uHfHCqLNwMZczUDsotxQMwGuSsGLtJ24Gz",
          "GkDY8Zg1Fvb3jgu2wTyBsoUbCxyYY1moJoUxAN8W2HrT",
          "AUQUpeGWEYJdmRVya13BYSRRyvZ9kKrMBp6WxWSX4SBb",
          "DjcRE1e9kfys25FPeRu4utwSDY9HJtU47XRydASoMMUA",
          "2kf3ZeBDQJpuNobQrHx9vZfzhJtoekwhP6vgJPdhAVeK",
          "53mPxaEZrXTB4DgJWci1mXXyPo81v3iQhfoFJoUwPqYn",
          "25DbNHKYmqNx1KvnU3xstqMX9KvnJEyAAExdMRxUX4j3",
          "3F5LLpheQvgZZ5vfQNUFyZRgqHgM898etbTtgpjPQ6yE",
          "DhkQEYnqKMLjFwPDqXH4xHUt4vbGT2DQWt6QEUa2US3q",
          "HPVp1aKY8vBVYkWuegbeoUGp2UX2ZmdwGVVz1gTj9vaz",
          "DVwf82CXY4icrVRUxJpqGhVqqXsFzBtgWQptHzAfHzKY",
          "4cwkpuqNuiZTrdW1qQeZPRGkj6AHghtd4NxK8ZYhzRPm",
          "8wePAs92Uzg9GnevMj715vFc66fFJCFmXFMcG29x9pCL",
          "6NFBSGvV7XFhYcoZPZWmxne8cUAemjoQ8zbDKC6dFUnQ",
          "4UdWGhDNAG2abgzi6zJ3h1y64frv5jsA75tJV6usZ83u",
          "EszKEbJKDHVenKdPp4rmp1eAi93BYFnTn9xhCa9FkRDQ",
          "DaF3oAroALqzf7ZGwWyXzbM1KhSqr1v9RWFEPwxj1umo",
          "AGrX3fzPVPCqUqb1r7M4tvWJFdfAWWiQzxVCwkyXDNka",
          "6BwQMGuhH5z6TAAkcVw2nzR2yJEH1Z8keagAbWjaZnzo",
          "85MwqWGEK3atMqLVHToXaS6Y35tKCGV9Q9JoR8mPhAEV",
          "38FcHy4LVBpjqPXLGuzLc3G4oE1pUdeB481Av1PHrDLC",
          "BQBV492pDPqUAj7jpUt7D4MbaxyLmV9tznyhptu9edWZ",
          "5u84tXfrY2UNp8djHVehCf5Y4EVX1QVbRbsLGsAEtfRz",
          "6Kf39sZLsdaPWVTwUSLXhmymaGcSSFNXkhQMExGu6qC2",
          "DNQFeDn9g8TY13JXjJsj87QsRZWCefdc1vbRp75dmXvn",
          "5oYLsjMnd3jArSEzb6vZbQo38x75nbg7jSkFaEabRPar",
          "5Pueg9r2nMKeCJ8B2FjKA7tG3vix2jy3pv3Pw7yXhboq",
          "4rurhcEAR2CfaGwkMKXhPNELnZ14FMYEmPsCK5ZhoQBB",
          "9Q6LAuprVv1p9SHje9zudyJJ8aWfrHZ6eAvaSPTtysCh",
          "FL2TY39r4YyPwVmfmfQF4T7ihXufwD6QfySvzQs9QG4U",
        ],
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Volume Solana Bot",
            icon: vsb,
            link: "https://t.me/volumesolana",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "The cat named Nala is the Sharkcat too but ya don't know that she is the famous cat on Instagram",
        ido: 1,
        time: "2024-10-03T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/No1InstaCat",
        tw: "https://x.com/No1InstaCat",
        web: "https://www.instagram.com/nala_cat/",
      },
      {
        id: 13123331232,
        table: "pppproject5",
        name: "jiffpom",
        logo: jiffpom,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "The One Signal",
            icon: theone,
            link: "https://t.me/theone_signal",
          },
          {
            name: "Kong on Chain 🦍",
            icon: kingkong,
            link: "https://t.me/Kong_on_chain",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Panda Caller 🐼",
            icon: panda,
            link: "https://t.me/Panda_X1000",
          },
          {
            name: "MUMU THE BULL",
            icon: mumu,
            link: "https://t.me/MumuCaller",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "No 1 Instagram Dog on Solana",
        ido: 1,
        time: "2024-10-02T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/jiffpom_1st_instagram",
        tw: "https://x.com/JiffPomInstaDog",
        web: "https://www.instagram.com/jiffpom/",
      },
      {
        id: 13123331232,
        table: "pppproject4",
        name: "ESTI",
        logo: esti,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Memex9999",
            icon: meme,
            link: "https://t.me/memex9999call",
          },
          {
            name: "💸 Money Maker 💸",
            icon: MM,
            link: "https://t.me/Money_MakerMM",
          },
          {
            name: "Master Cat",
            icon: mastercat,
            link: "https://t.me/MasterCat_X",
          },
          {
            name: "Dracula Gamble",
            icon: dracula,
            link: "https://t.me/DraculaGamble",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "ESTI is the real name of the dog that inspired Shiba Inu Coin!",
        ido: 1,
        time: "2024-10-01T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/EstiInuTheDog",
        tw: "https://x.com/EstiInuTheDog",
        web: "https://estisolana.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject3",
        name: "BEBE",
        logo: bebe,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Wulfden",
            icon: wulf,
            link: "https://t.me/WulfdenX",
          },
          {
            name: "BABY CALLER 👑",
            icon: babycaller,
            link: "https://t.me/BabieCaller",
          },
          {
            name: "Weibo Gambles",
            icon: weibo,
            link: "https://t.me/WeiboGambles",
          },
          {
            name: "Travel Caller",
            icon: travel,
            link: "https://t.me/TV_CALLS",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "Unleash Your Creativity with Bebe!",
        ido: 1,
        time: "2024-09-30T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/B_E_B_E_S_O_L",
        tw: "https://x.com/BEBETheFroggy",
        web: "https://bebetokensol.fun",
      },
      {
        id: 13123331232,
        table: "pppproject2",
        name: "Repost Cat",
        logo: rcat,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "The One Signal",
            icon: theone,
            link: "https://t.me/theone_signal",
          },
          {
            name: "Kong on Chain 🦍",
            icon: kingkong,
            link: "https://t.me/Kong_on_chain",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Panda Caller 🐼",
            icon: panda,
            link: "https://t.me/Panda_X1000",
          },
          {
            name: "MUMU THE BULL",
            icon: mumu,
            link: "https://t.me/MumuCaller",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "Let’s break a world record together and get the most reposts on a single tweet. The current world record is held by the Mr Beast. We can do this guys",
        ido: 1,
        time: "2024-09-29T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/RepostCatSol",
        tw: "https://x.com/RepostMichiCat",
        web: "https://rcattoken.fun/",
      },
      {
        id: 13123331232,
        table: "pppproject1",
        name: "Smoking Chicken Deng",
        logo: scd,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Memex9999",
            icon: meme,
            link: "https://t.me/memex9999call",
          },
          {
            name: "💸 Money Maker 💸",
            icon: MM,
            link: "https://t.me/Money_MakerMM",
          },
          {
            name: "Master Cat",
            icon: mastercat,
            link: "https://t.me/MasterCat_X",
          },
          {
            name: "Dracula Gamble",
            icon: dracula,
            link: "https://t.me/DraculaGamble",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "He who holds shall be richer than he who has sold.",
        ido: 1,
        time: "2024-09-28T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/SCDPortal",
        tw: "https://x.com/SCDonsol",
        web: "https://smokingchickendeng.fun",
      },
      {
        id: 13123331232,
        table: "ppproject30",
        name: "Moo Man",
        logo: mooman,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Wulfden",
            icon: wulf,
            link: "https://t.me/WulfdenX",
          },
          {
            name: "BABY CALLER 👑",
            icon: babycaller,
            link: "https://t.me/BabieCaller",
          },
          {
            name: "Weibo Gambles",
            icon: weibo,
            link: "https://t.me/WeiboGambles",
          },
          {
            name: "Travel Caller",
            icon: travel,
            link: "https://t.me/TV_CALLS",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "Where’s my hug?",
        ido: 1,
        time: "2024-09-27T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/MooMansPortal",
        tw: "https://x.com/MooManonsol",
        web: "https://moomansol.fun/",
      },
      {
        id: 13123331232,
        table: "ppproject29",
        name: "MUU DENG",
        logo: muudeng,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "The One Signal",
            icon: theone,
            link: "https://t.me/theone_signal",
          },
          {
            name: "Kong on Chain 🦍",
            icon: kingkong,
            link: "https://t.me/Kong_on_chain",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Panda Caller 🐼",
            icon: panda,
            link: "https://t.me/Panda_X1000",
          },
          {
            name: "MUMU THE BULL",
            icon: mumu,
            link: "https://t.me/MumuCaller",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "Muu Deng is joost a virul wittl hippo!",
        ido: 1,
        time: "2024-09-26T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/MUUDENG_CHANNEL",
        tw: "https://x.com/TheHippoMuudeng",
        web: "https://muudentoken.fun/",
      },
      {
        id: 13123331232,
        table: "ppproject28",
        name: "POPLLY",
        logo: poplly,
        whitelistsShow: true,
        whitelists: [
          "EAwJrg6CHWg6atmZZizLeF72ajfskNLYNRsBo2r3neE",
          "EpscTEhcMwfeDeEMAX3xBwwFWioVibysqyxTSr1Lfdcn",
          "5Kv3Eu2NbkUbZ1AujEK5YB1J4jxMc1X9ErSpCd1ajCSx",
          "3NMDyv7qjR2M85dKehkDnfGwAAx7icfxx8jPTB8cf9GV",
          "6S7Kad614azpNR9uSHVq41PDeCxBAQxJe8XQfTqK2jn5",
          "29q6CfHSfvPM5NLuJmnazyLNVbeiqcrjDa3qVTU9ppW3",
          "BSGdFoXq8j9MYdZv1LSX66A6GqTJgpA72HewCj95GjMi",
          "49cFtzLe1MizaJJeEKYZ2BuWKoycDaEJDngizrJJbN3o",
          "4cvAVah9f66kxJzpStC64KV3DUPcK1HSL372bG1KXrrB",
          "6qgKYB61wjmRfXRR4ZvH7VHc9GezWC1iPDzZ5GuLiWeV",
          "BmGu5zXgQn9sDV9x97HDdS7ofR2rLGeGEzNESjjBfKoC",
          "3tqPSDYwmJpYamJUMGdWCUen57EFDhCTUHAdHjYy8dDf",
          "ErcniCdVpggdH2W513Er5pdC1V3FwNPLuHGMPAo4rZ3S",
          "E3Jv3aURHUZAVs8sm6FNbT74g1qW7sMLm8EWXSYBBARr",
          "HUBuhYgihtitU7sXdnXvKpWzRhkT4FEr3QttmLXjfnNP",
          "EtGb8MvdSThisqXRmiybYGUeY5grr7jnrk838fZj9ZYm",
          "6nYSccgHnCkA6Neizgnttqzux46pWJLZU693GG7K1vAQ",
          "3bRcZ8CXJSkrFyDPa4xkKRJ1tL2VensovSyxzYcoFXNH",
          "2v9az38V2ynF2voxf6MwNsWzAuhTLBWq99CubJCgxQnT",
          "2ssZShRERsTrrpemV3WqMm7LSb6ENSGoRB5zNmpPZ2dD",
          "AmckGFZLfn27rxNMGqWWsDYuoyGsQrdhV5MQvh8Rm4Cr",
          "Ct3PDmHuSvdhjfCBVowc89FKvbjMANp1HEAzRNrKcP1P",
          "6NNxbPJntJzhpL4oPrUEyyEeaEpxEbZDMnB1tevnbpiu",
          "GrPw2hwUW8rSHxv5LyCoSY9DJHBpKoNiY5S5AtxVWq6C",
          "AvSF9oB8jpbWh38Q7PEB35geMVuGVkXgcPvnUrnbJ2dr",
          "2YHwZWrgME6CxfsXGq79NNrEtWUGPpNyoQv3mVY8hKRY",
          "29F3yJ6zxamwBxW3yqgVyKx9ubKviwADgqNkkGSzGvZM",
          "C917kkhZ46uv3JeD6wK9otd6A3M5g62ELNK1m6sSyn7o",
          "6DyfBcEqGmgpyAzM9PBZE6TTBvS3Hc9Szea7TL43oLDo",
          "6kLXXeiNe6QPfArG6qe3MPyoL8xzSDdtnRF5qAoorCNH",
        ],
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Master Cat",
            icon: mastercat,
            link: "https://t.me/MasterCat_X",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "The Billy dog is popping because he gonna be listed on Binance and he becomes Poplly",
        ido: 1,
        time: "2024-09-25T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/POPLLYPortal",
        tw: "https://x.com/ThePopllyDog",
        web: "https://popllytoken.fun/",
      },
      {
        id: 13123331232,
        table: "ppproject27",
        name: "wrapped Deng",
        logo: wdeng,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Wulfden",
            icon: wulf,
            link: "https://t.me/WulfdenX",
          },
          {
            name: "BABY CALLER 👑",
            icon: babycaller,
            link: "https://t.me/BabieCaller",
          },
          {
            name: "Weibo Gambles",
            icon: weibo,
            link: "https://t.me/WeiboGambles",
          },
          {
            name: "Travel Caller",
            icon: travel,
            link: "https://t.me/TV_CALLS",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "Wrap Yourself in Fun with Wrapped Deng!",
        ido: 1,
        time: "2024-09-24T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/wrappedDeng",
        tw: "https://x.com/WrappedMooDeng",
        web: "https://wdengtoken.fun",
      },
      {
        id: 13123331232,
        table: "ppproject26",
        name: "FWAGA",
        logo: fwaga,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "The One Signal",
            icon: theone,
            link: "https://t.me/theone_signal",
          },
          {
            name: "Kong on Chain 🦍",
            icon: kingkong,
            link: "https://t.me/Kong_on_chain",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Panda Caller 🐼",
            icon: panda,
            link: "https://t.me/Panda_X1000",
          },
          {
            name: "MUMU THE BULL",
            icon: mumu,
            link: "https://t.me/MumuCaller",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "FWAGA: Playful Politics, Unforgettable Characters!",
        ido: 1,
        time: "2024-09-23T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/FWAGA911",
        tw: "https://x.com/FWAGA911",
        web: "https://fwagatoken.fun/",
      },
      {
        id: 13123331232,
        table: "ppproject25",
        name: "LEE ZENG",
        logo: leezeng,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Memex9999",
            icon: meme,
            link: "https://t.me/memex9999call",
          },
          {
            name: "💸 Money Maker 💸",
            icon: MM,
            link: "https://t.me/Money_MakerMM",
          },
          {
            name: "Master Cat",
            icon: mastercat,
            link: "https://t.me/MasterCat_X",
          },
          {
            name: "Dracula Gamble",
            icon: dracula,
            link: "https://t.me/DraculaGamble",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "The baby Rhino Lee Zeng fit the zoo portfolio for sure. He is real and he is cute!",
        ido: 1,
        time: "2024-09-22T15:00:00Z",
        totalRaised: 10000,
        tele: "",
        tw: "",
        web: "",
      },
      {
        id: 13123331232,
        table: "ppproject24",
        name: "POPDENG",
        logo: popdeng,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Wulfden",
            icon: wulf,
            link: "https://t.me/WulfdenX",
          },
          {
            name: "BABY CALLER 👑",
            icon: babycaller,
            link: "https://t.me/BabieCaller",
          },
          {
            name: "Weibo Gambles",
            icon: weibo,
            link: "https://t.me/WeiboGambles",
          },
          {
            name: "Travel Caller",
            icon: travel,
            link: "https://t.me/TV_CALLS",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "just a viral lil pop",
        ido: 1,
        time: "2024-09-21T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/POPDENGPORTAL",
        tw: "https://x.com/ThePOPDENG",
        web: "https://popdengtoken.fun/",
      },
      {
        id: 13123331232,
        table: "ppproject23",
        name: "Catgo",
        logo: catgo,
        whitelistsShow: false,
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "The One Signal",
            icon: theone,
            link: "https://t.me/theone_signal",
          },
          {
            name: "Kong on Chain 🦍",
            icon: kingkong,
            link: "https://t.me/Kong_on_chain",
          },
          {
            name: "MemeX9999 | Gamble 🎲",
            icon: meme,
            link: "https://t.me/memex9999gamble",
          },
          {
            name: "Panda Caller 🐼",
            icon: panda,
            link: "https://t.me/Panda_X1000",
          },
          {
            name: "MUMU THE BULL",
            icon: mumu,
            link: "https://t.me/MumuCaller",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "$catgo on solana",
        ido: 1,
        time: "2024-09-20T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/Catgo_on_sol",
        tw: "https://x.com/Catgo_On_Sol",
        web: "https://catgotoken.fun/",
      },
      {
        id: 13123331232,
        table: "ppproject22",
        name: "MISHA",
        logo: misha,
        whitelistsShow: true,
        whitelists: [
          "GTfVqPg9UymRUYAYtBs2qcrhJ7oVpA9Xp56wzoMcCko3",
          "S8ZTqmZYGbMni1r5WEnm7Kr14yUvZ87W6fw5wN2DuBX",
          "Gt2stnYftMFKmfeNVZ6wtPNdyn8fw4uZqw2PJuWE8GZE",
          "7PvRTrwuzbN2jj5QK7M58o41rMizozSFiFoFesZaGoGG",
          "GYeiV7HU5G96eKXCvAET63iU3KY8bnRXnuwHy3bctSGh",
          "A9soaPRVHNAeGJDwwDEtNmzBSx7Rhdxw4P99fR4pootW",
          "7g7pzTdGVb9EZGVhTshJSKdS7vvbLt2DU4RDssZVGqS8",
          "HiYoic92VwiTFK3ecPnEyKPpfZES2E1jmdPEzhUCzsmC",
          "CyVkG6GNfSsLGryoUEGizEWebCriN99HwYrqiSWVpQs2",
          "HphdctLPqnkxmo3P8M391KxU5MvWkhG3NFf2xzWGxBFB",
          "2LEzEXGKdawo2AaftFoKQgimpHB2nAwExBoSbPkXPQHp",
          "2m9saP13gMM4d6ENY6qT3XgPrGZT9HFaerL37p3tAf6e",
          "BobZNgUjDT9ScAEYo48xrfGjhdGmgf2Y2iagrv8HbNU2",
          "3aF5SJAVNfs19FdsYg2pkasJDfhvr6GpbQsvSt949md1",
          "EVmsoZkCC7d3mFYg96AUPNFJgoJVUq7N4NTQFcLRpCcf",
          "EhvZzjad3gPHMvru3jkbTUAmmcHr7t4FRdxC96uEdRwz",
          "8FpRug2rHX4GHfpdaRVJzazJjNCFhWFqT2omnzcxT4aG",
          "DRtj7abqZAjrJm7S4UFDUxxHqS5G9mm55sNVUyq3HehA",
          "meYy4ibeaATnVBqeRjjjkfeNWmxpC8pn5ECbfPRmhh6",
          "5YppA1L1SLb6MSkhNFw8SZtaYiCcFtGLTLE7shqyByaX",
          "9wxUri3LrqVhwpSS8Gjmbfm7Kza9CcnbXAfJdT9YYgue",
          "DyyB3FFFWVZKpoLNa5GVb1PtR8mKsFBDzwWRyFho5tSv",
          "Fencp5DKos4WA8ygQJH8XwZGEigNBLvjkERUtbs9Xk1D",
          "42xj9puaER6DXMLLcwpHTtWDzCQutamgYnoPEWVCxEMr",
          "E1PLGCDwgaJz34htj3HvtBfUUBbYQ16F5Ar6UK44X4Zs",
          "DEdMeyMd3YFBrqmxqoKiJgC2HLA9cibhnLwq1oZad91w",
          "2mUv1BoCXTRbp4LcSnJCEZLJB7RcioTmd1vWfdSNARqU",
          "14V3w62JniQpfKRhFiHyxfJGaEMfonQRX4bkhmC14uPR",
          "GzAiMHDHGXqdUMGqAV82C96DCot5zEKqP3W1w5Nqkoen",
          "37JqNDgM76ZTuMN86VKW8MjfHugEHv1DvwbGNLvrHp7f",
        ],
        tag: ["Safu", "Audit", "KYC", "Doxx"],
        marketing: [
          {
            name: "Memex9999",
            icon: meme,
            link: "https://t.me/memex9999call",
          },
          {
            name: "Add more",
            icon: whitePlusIcon,
            link: "https://docs.idosol.me/2.-unique-features",
          },
        ],
        des: "Hi i’m Misha, Vitalik Buterins one and only doggo 🐶",
        ido: 1,
        time: "2024-09-18T15:00:00Z",
        totalRaised: 10000,
        tele: "https://t.me/MISHA_PROJECT",
        tw: "https://x.com/MishaProjectX",
        web: "https://mishatoken.fun/",
      },
    ],
  };
  const [dataTemp, dispatch] = useReducer(dataReducer, initialDataTemp);

  return (
    <DataContext.Provider value={{ dataTemp, dispatch }}>
      {children}
    </DataContext.Provider>
  );
};

export const useDataContext = () => {
  const context = useContext(DataContext);
  if (!context) {
    throw new Error("useDataContext must be used within a DataProvider");
  }
  return context;
};
