import React, { createContext, useContext, useReducer } from "react";
import maple from "./images/maple.png";
import meme from "./images/meme.png";
import babycaller from "./images/babycaller.jpg";
import forsages from "./images/forsages.png";
import goldenpepe from "./images/goldenpepe.png";
import joewifhat from "./images/joewifhat.png";
import fushipepe from "./images/fushipepe.png";
import akita from "./images/akita.png";
import tromp from "./images/tromp.png";
import pengwifhat from "./images/pengwifhat.png";
import shinhan from "./images/shinhan.png";
import pekachu from "./images/pekachu.png";
import renaldewifhat from "./images/renaldewifhat.png";
import bookofdoge from "./images/bookofdoge.png";
import kingmeme from "./images/kingmeme.png";
import snappe from "./images/snappe.png";
import anapple from "./images/anapple.png";
import pengisking from "./images/pengisking.png";
import smoly from "./images/smoly.png";
import fineandsmole from "./images/fineandsmole.png";
import mastercat from "./images/mastercat.jpg";
import theone from "./images/theone.jpg";
import MM from "./images/MM.jpg";
import battle from "./images/battle.png";
import whitePlusIcon from "./images/icons/white-plus-icon-3.png";
import fifa from "./images/fifa.png";
import moby from "./images/moby.png";
import yellow from "./images/yellow.jpg";
import pepeonmoon from "./images/pepeonmoon.png";
import panda from "./images/panda.jpg";
import travel from "./images/travel.jpg";
import { dataReducer } from "./reducers";

const DataContext = createContext();

export const DataProvider = ({ children }) => {
  const initialDataTemp = [
    {
      id: 13123332,
      table: "pengisking",
      name: "Peng is King",
      logo: pengisking,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Welcome to the world of 'Peng is King' – a unique memecoin project that adds a whimsical twist to the cryptocurrency landscape",
      min: 1,
      max: 4,
      time: "2024-03-21T15:00:00Z",
      totalRaised: 150,
      tele: "https://t.me/PengisKingChannel",
      tw: "https://twitter.com/PengisKing",
      web: "http://pengisking.xyz/",
      contractPresale: "3t2cJ1uqZypuuPAQp2gn7beVCs72fQqtm8QgVbi24pMh",
    },
    {
      id: 13123332,
      table: "smoly",
      name: "Smoly",
      logo: smoly,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      whitelists: [
        "ABkE3sn23UAzL8teRE41MYVq6KNPWzkX3Uj3rWtEGNFw",
        "7mqbMg3QKc7tbrLLAr6apSPATxGbrUqBih5hYEMGzHTi",
        "9v2VsEKSiGVGgn2Cs5et6RrW4J3iiN2PvM8T9r7baWVt",
        "7AjWBwToLvFWsX6VTGPdYhY5yczmo63G3c7iwYM8jxBS",
        "6u3qWsHfK7NxxQG1814Fq9JMVvcyTjpmfb9Zh2WWQYF4",
        "DwMVDnLQaTR2kU4nNnzwQ3iJbU1BLEYKbiP6tApaLTTU",
        "Db2EWVNFpeqDTUvwHSLxtP29pSjNQyDBKowS9SeUnqYp",
        "5vP9XdbGKU65QnXga3UQhA2Mn5puy7W59qTUDCQXmJwd",
        "CcmYrfxprDtzvcsu1T5M5gUHpqG1UnmbAFB6bQqhcb2J",
        "5JoMecXjYZtpqwFEMjZDkFCzTaU5fLoi2XWBL6sEpQS5",
        "4xw7k3JUnCuVoq6pFZZkmCzgRURtyMTCSCvpFkxNQGVp",
        "6ARDhdqTpU6cVhwrT8bxqA1SqBncFw1tNtAUa2EVvsDg",
        "3BymtcDP8MW2LBA2gy5hvzkGMneWHVEz8gdps6do1x9j",
        "HwQK8UFnpVJ1C4THMp3poSmrNHVmZd3ZhLg5gFArHkAe",
        "Gei93EhFT1uZo55Tf1ACMY7SUDRUfMFN5FX3VDBd1vcL",
        "9DvBZCGQdgGCRP4R231LMZQPGmg7khH3tox4szeTDhBv",
        "GYeiV7HU5G96eKXCvAET63iU3KY8bnRXnuwHy3bctSGh",
        "9qy7wn6LXFUMwsFBMQKgw8G7oGuMxkm5KFHuB6LFz2Yn",
        "3j2ctzJkcr4Ksv9gdYguHQ3Ci59oceRPyQd1whGR8dWJ",
        "3nD84yfFgN4SJnzwN841edTmGJTEz6Ho9vYJfTHT85am",
        "Gqsf8PG4aTB8fXo1cnLVN61egCwv4x4P2tC3tLgNZSx7",
        "2eiJ3CajidbXCH2JXEBmKQqZy44r4W5HsQRixLg7egLb",
        "GYeiV7HU5G96eKXCvAET63iU3KY8bnRXnuwHy3bctSGh",
        "4gAjhXtaWqc3hCJDYiMp2XZ1rQJjnHjZYTWoFusVbUoM",
        "4uNKW99a9jVnjegHvi1Wg5MWfahgZgBEwkLumYnidfMo",
        "1VUdqv6xFrEroAegD8pF1JXp9era3yd2buwTpWXTFoc",
        "2B2QwpRkonKsM19PjWCCkg5WmwLQyNJ7sgogFEuJ16tw",
        "5cYtrCPchfw8w7dFyd4ondxMwWFWQ163pWtvGKY1dD7G",
        "AAQVdxEuQhLfQbhx9JEa4FMHp8xpoGrtrCksVbM26yBF",
        "FQ5vra631FL24L9AHwodZKReKVETiV6RCbngjrCahDoN",
        "C2eWGWrcLRKpCg3jRfcZ5Z9HRHKHa27efuW87CQ9Yzf1",
        "BTp7S74z3Ff8CL3ezkiCy39SqLGnSu3n1DGcicztLmtq",
        "C6BAXF4FVE81EaoHTju2XDZLDPTXndToGNyfzM8ePhUg",
        "J9Qo9suaypwTuGrBYguG63nk4UBQkvv7wH4wh4yc55Gd",
        "Czm7NqLiaEvNkTnMvWmMpQL2vp6DrPWSQgXJdXqqSfJS",
        "88dVrLeL6cTn8pEciG98QSKADYvCiGRR4hMAGEqANkSz",
        "DtSLmoYVvgajW8RFoHWbDikhrHwGEAUtKbtX4uN2bN7d",
        "Fmho4UHMhxnm6z4fQFgf4fnHLMgWDzWRhkZrSUP6UutS",
        "G1KBc334ZiV2XD5GQmZtpVihGrG1n65W99aYtHvfuSfp",
        "4hzWkq9XMF5BRsLYTXW2mD6bFD2BWxoyjmh6WtdrEQbb",
        "FkqYWj1nBWYvzWmadTTGUSHw9Ljh147UjMbZaHjsRTbD",
        "EyafKJE4T9bGbSEDs1JTE76h9cQJwqJkxa5wqHmU6Cd6",
        "9My8eMVECRDjGqjJSEERY941HEbshvPjFQvcMbJfq3eR",
        "AF11Ygqg2VkiHAgYbeoHBm9QVJBCsZuwotgBaxhiUXJc",
        "HNtJcCkgXSw7xdXgJoYqPHnGJwyrAuFRm6heVwGjALoZ",
        "HTi9qvvoWpB8FTGeaLDJSAatZ7r5ESzRS7e63iwZ2n98",
        "HyAoVJE5NRyeRTjGdpx11DRNwuAuqmM34NgiMyhbcP4A",
        "FG8kEAt8B3y35Lvstu5cV4zHdKMy7i63KNYC2q7S2HGV",
        "9hon9vpwdUwM9VaYgJkXeMV7Rxoy9PqzG6i2QgCdjr5A",
        "6BV2Gqkk89xjCgWSVd24a1xjCHPJKpJnUzAvmyrcS9Zm",
        "Hc8fmpMXRFvz4VyaVSifnwx6LhGD6EZBqoTZDgXKY25F",
        "9XBxF9rydTc6p5f9bZ6qoj59p1LwjRHPF1qjPSRMK2Sz",
        "6DjbKKDpjL6GxqY3CdbzhMptzHYKhNG7yjz32iLrfaK5",
        "FCdGg8rdezHieUb5RmrdEG4AsbVKYSP4956QhksoA2fM",
        "BqThCwjKpPuqTjadeg7CnQLWbk8f6JsvdDrxwkwtCwjb",
        "EeknpgCEnDsjCsVUYy3PKT8TNcz3FCf35DQZNWavmAYn",
        "J2Zi26t2DpANfTBAfNNm1mLbjLGETAQDFiqXtpkt2MSS",
        "GRgSwxSaBwQbXQjwjhtqr6ne6XhoKor7iCe7qoiDPNTD",
        "78s8rwJmnZ75yQaMmMSAkkYL4D824H6vaBH7sqKvt8F9",
        "247qj1R8R15fN1hdaubcSrBMZNKzg7QH7yxi6NLCkxKS",
        "72ho18HjGRavJc81DjUNN6bdRADT2catx3bcTEXMQpaH",
        "4anVRRLdELQ5RhHaPHzc32LsBY2DUZNWqc6YjrLrvA8H",
        "8xBkZ2A9q1tLyLSNWuKuVDajbfEeLbJ5FFGtSCTMJ3EH",
        "9wbbLnxGdsGmxGiwbyNQFhPGHC6eM3b2NvFd8ZLfDVpg",
        "4Tz3YfsyJP5uqtzc3CjXTQLsg6ca68vR2Xtci4pXzMGE",
        "Cip7KCKt5ys9XbdEJo2uLNeCeVybKstWikDWHyZnYsY8",
        "EWthNqty5EAEzaNzv4rWyoZGtgRaFBDDSe5RGuRzwcqS",
        "2en3coGEEe8XkcSaP5PRTmiQ8BHfyoNVrRRKR1JNaumj",
        "EtUZgUbXxqpaCvkCXt6q8Tdd5MzB8eL2XhT5JfF66fEc",
        "7pb4vWKPxDs56gjkZWEC1NnjcwHSEF1EiSMPAMzbAQDL",
        "LSxMCZP9tqR2wBzWnhBd2hc9VYrfzKpknwQcZdR1kvw",
        "4jzsryJAkh8GwDqooT45wP13iY9h5gtt4EjE8Ejbsmhs",
        "9yaQY6dD3YhYULAZhVCNkxcxPtJbRUcMRo7MGwGJz8z7",
        "J9SqKvsRCaqGCAJyxnS32XQCjuzdefHaEQRTr7StMQ6u",
        "HJyk7qnZbC2ut725q9waooNoe1FS7tZbR5gZTsJNThZL",
        "BgceupnQZ7phARoRT35coNiRKrK5TCypU42SjE7HYAXi",
        "5GtdKd6M497GzZia9jXPv1qUq7ow6UvqUuM2tghLJGnP",
        "7ycUu3R9TF8HWr5pQqFVjWvd78KM6kcN9kUeQKvfp2nW",
        "Ht5xoAteCpqfpUTgajEARVB63tDEksa7MKp4j9jAzKEa",
        "69Dtp6hTbozka9vX6EK34hAW1PckZR9y3M1x9XP2xfAs",
        "2krMXGZbXw3ATig75U9HRVUYakXUNW9QBNT82ovZdK5r",
        "8jbP4HHtaKFNw54KNqXbDc1Av3xMrj8JzQkEDjwh4tEM",
        "AqatCHShJ1MG21AKjHF2aywErFJ8HzDzDmceg2nEvQWw",
        "7CnTSLm1ybVqdaTAzX8CQYafNWG3eqY2VHsGJgmKzmZw",
        "J5acSLpd4KxBJsbfL2AdQ21LusA9j4AfyPtV7DVDNCHo",
        "7pbX7Br3G3fNYiuJnhATkDZmA8w7QF4k6B2MefcdahuL",
        "J1G7RBxus56mXVLfTLtfCLEFuEbYKPPXaf1fqFc7tYLC",
        "Bkrn9ncYBLRMsTCg5P793vo3C9Tm8EYXXLppdmunyAv9",
        "JEFXq6SyLomno7uXZGRBTdSBNAJh19uv3FoF3o596aYq",
        "2ox3XtMCc9k93MyNo6f6ibCfgAM3YZBMs85AeQrYFgeN",
        "EU67NyQhc6ASynSYoTwrbnja5QeoYsy5hYYjDWx9C4Li",
        "2zKnBovBZckBhiU7Yc8uQpShCA42aTyrWuVCVDwYkzZu",
        "2Kw6Z4kU9Dppg6eYHL3oGi7WAod2pisvoe8DKq6CtygK",
        "GFbYwuSAgK5g5BfVVb4pr6DgsXbcruVvNjHh8BusNpFm",
        "6xtH5qzfpc17MLA2SEnyiq5WhyHS3EVKBwLJYd3ijQ5S",
        "E75jnaeKfsqQDsKn9mzv7jaB7mFs3PmaeA3FAgVhykHu",
        "HiM8ygM9BcemUmYfKDp2sGjbb3nRkJzxoZEQVtEuNRMt",
        "FxLredJrw9frRYTidDX6JjQkvrzQubcdEgnnuyJGeczX",
        "Fb1Tsce8WUsSdwhtBqCe5fF5A6DhMq6rJcNcrgtD4ygy",
        "GKxZKEVsHUQdovUe2pC3Es58pJcMsTfZtARzyJXug7Dh",
        "4MeXmKXDT1wh9Z9rb5GjauTRbCnwFJmorCws4y3way1o",
        "APDZggSBB6SfFADm5TkNGYWkukhoisfz1FRuqMRphq9x",
        "65gkJBGF5iWLrf94qzqVnZtXiCMirZwpebuawWEG6912",
        "5Fi2ogsTWMZUxGcH8pHXrvZkc5UrHAtZKqoXKjohXjUg",
        "5iMLQptghMRZc2ye1iT8rhHdJs3TdxK5SqCrvgwY7WxY",
        "h9gUFXAWHEhV6m2KJ8F528gGfMPwzCvTFNfRpE6t5nr",
        "ETLjDKDaQbQem2D8z64TkUdj8KyLhdffRGfwmxhkL5FJ",
        "Gdj4D2Spx6fHcHtCunY7bTKjz5RWGEkSTywmVjLTcG4c",
        "NMDo1Mfgj8KVXCadPJaxpdFV7Yz6pQ9cRV71BqSmuca",
        "A1ER5GWwRcC6iFHMwiJBAk6EXFvhEa64FQ6uPbNgNSHB",
        "5W3xtfpqu7VnkWKbpwM7dJNJKxiifgwTp9y2atJfFZMH",
        "DhK2BgbfKivh3dFdtukDMTuagaPLxAiYX17jg9ZFNk1u",
        "4eLj3HuFRUy2oyCL4B1tYmN9bFtxetNhwyWT148ZQqZP",
        "CZc6oovBTgpgfwJueMQJ7rug44UrZHTET7wkq1bGbUVc",
        "3kjiJ45ovi1bVKAESRoFqCJ7E7goveaprQBXBVzXgd3X",
        "HFvM1cnMaa346YpSPnqmoFLvRQfqTrpM8KA5CcJ4zaup",
        "AxhHDCqdp34qgMKnkgpff2VxafezdTatkidd4ErDnVbp",
        "EXwxvvo5so6TVRAQHf2UrBPSc2aMg9xwm7nys1RYc9Wj",
        "CYsULgq4J6Vh5LpZJRpukZE5g6pczbBj73bkx7uJhQY9",
        "5sRhDjaunrRTha8tqEBQorQuMsr6DqneKGshnAeFcnZG",
        "8Zo2mphBA1QiPD9DBD3MGD6QDS8hA6iP9epSntx63Ghj",
        "qb1kCw54dT4kmux79G7NTPJ8qPn8jZLmWkVcaps4FjT",
        "6RGL6yK12bkZw5CFpCZRULTnyCB551g7PMkkbp6uCQQd",
        "Eo1zSCCfFHPm2v5TyUkcLChHFrLvqziurjQWTGkusGBE",
        "BED8jYpDzqBJ2DbVTJy1S2U9TL9SxtTpGaqLoNm8oNmj",
        "29bjzWX1ihtWv89gQKWdnoFcVi2FTWeVeecqZ8EdWFgW",
      ],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Smoly brings charm and excitement to the crypto scene",
      min: 1,
      max: 2,
      time: "2024-03-20T15:00:00Z",
      totalRaised: 250,
      tele: "https://t.me/SmolyChannel",
      tw: "",
      web: "http://smolyonsol.xyz/",
      contractPresale: "3U7WVgWL1aURjdmJ273ehkTZnDEewVojeRs9Vng7G1UJ",
    },
    {
      id: 13123332,
      table: "fineandsmole",
      name: "FINE and Smole",
      logo: fineandsmole,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "This is FINE",
      min: 1,
      max: 4,
      time: "2024-03-20T14:00:00Z",
      totalRaised: 150,
      tele: "https://t.me/FINEandSmoleChannel",
      tw: "",
      web: "https://fineandsmole.xyz/",
      contractPresale: "EefJtqjNZRRf8LzFNSpRW76Xxo3t3DQL4shcaaBhaaQD",
    },
    {
      id: 13123332,
      table: "anapple",
      name: "An Apple",
      logo: anapple,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "BABY CALLER 👑",
          icon: babycaller,
          link: "https://t.me/BabieCaller",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "An Apple is a wonderful thing",
      min: 1,
      max: 4,
      time: "2024-03-19T15:00:00Z",
      totalRaised: 150,
      tele: "https://t.me/AnAppleChannel",
      tw: "https://twitter.com/An_AppleX",
      web: "https://appleonsol.xyz/",
      contractPresale: "G9sJ8aXSbzhYqwau8zzjQXHeVwLThoY4Rtj3ujEJ1KQi",
    },
    {
      id: 13123332,
      table: "snappe",
      name: "SNAPPE",
      logo: snappe,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "SNAPPE is the best memecoin on Solana",
      min: 1,
      max: 4,
      time: "2024-03-18T15:20:00Z",
      totalRaised: 150,
      tele: "https://t.me/SNAPPECHANNEL",
      tw: "https://twitter.com/SNAPPE_",
      web: "https://snappe.tech/",
      contractPresale: "Ga4iEBvGazbVrve497h3YWq38pU32rrQr8U7VDyp76oB",
    },
    {
      id: 13123332,
      table: "sulana",
      name: "KING OF MEMEs",
      logo: kingmeme,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "SULANA is coming on SOLANA!!!",
      min: 1,
      max: 4,
      time: "2024-03-17T15:30:00Z",
      totalRaised: 200,
      tele: "https://t.me/KingOfMemesChannel",
      tw: "https://twitter.com/KING_OF_MEMEsX",
      web: "https://kingofmemes.net/",
      contractPresale: "2Y3UR8yCgWPkjojc1cevRy2ZXURFjYjGF4BsuJHgQ3a9",
    },
    {
      id: 13123332,
      table: "bookofdoge",
      name: "BOOK OF DOGE",
      logo: bookofdoge,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "History of Dogecoin",
      min: 1,
      max: 4,
      time: "2024-03-16T13:45:00Z",
      totalRaised: 200,
      tele: "https://t.me/BOOKOFDOGEChannel",
      tw: "https://twitter.com/BOOKOFDOGEX",
      web: "https://bookdogsol.xyz/",
      contractPresale: "XkAhK5kVpX2v4uZiyynwPsxYdxhvMXF1HqkXTakTgCf",
    },
    {
      id: 13123332,
      table: "renaldewifhat",
      name: "Renaldewifhat",
      logo: renaldewifhat,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Siuuuuu!!!",
      min: 1,
      max: 4,
      time: "2024-03-15T15:00:00Z",
      totalRaised: 200,
      tele: "https://t.me/renaldewifhat",
      tw: "https://twitter.com/Renaldewifhat",
      web: "https://renaldewifhat.fun/",
      contractPresale: "HB3WxaexzWpR3tHQW1zsg45dE7YNZxsSt9P676yDw7mb",
    },
    {
      id: 13123332,
      table: "pekachu",
      name: "Pekachu",
      logo: pekachu,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Pepe + Pikachu = Pekachu!!!",
      min: 1,
      max: 4,
      time: "2024-03-11T13:00:00Z",
      totalRaised: 200,
      tele: "https://t.me/Pekachuchannel",
      tw: "https://twitter.com/PekachuXX",
      web: "https://pekachusol.com/",
      contractPresale: "Dqv3RWFugbupmBArUEVWd8j78gGCeHu1uhfBfSBcHjf1",
    },
    {
      id: 13123332,
      table: "shinhan",
      name: "Shinhan",
      logo: shinhan,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Tien Shinhan, often referred to simply as Tien, is a prominent character in the Dragon Ball series created by Akira Toriyama",
      min: 1,
      max: 4,
      time: "2024-03-08T15:00:00Z",
      totalRaised: 300,
      tele: "https://t.me/Shinhan_X",
      tw: "https://twitter.com/Shinhan_X",
      web: "http://shinhansoltoken.com/",
      contractPresale: "BZRdtLGcoW48ceVW151KxW3wzADSymkteebvSrYP5Mnm",
    },
    {
      id: 13123332,
      table: "pengwifhat",
      name: "Pengwifhat",
      logo: pengwifhat,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "HI, I'M $PENGWIFHAT!",
      min: 1,
      max: 4,
      time: "2024-03-07T15:00:00Z",
      totalRaised: 300,
      tele: "https://t.me/PengwifhatX",
      tw: "https://twitter.com/PengwifhatX",
      web: "https://pengwifhatsol.xyz/",
      contractPresale: "Dy5bkpxCmFbxtg5tcEBjLtAXkWqhAMtgHG9wTLyp1Rg6",
    },
    {
      id: 13123332,
      table: "supertromp",
      name: "Super Tromp",
      logo: tromp,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "$tromp own onli tromp nd be happy",
      min: 1,
      max: 4,
      time: "2024-03-06T15:00:00Z",
      totalRaised: 300,
      tele: "https://t.me/supertromp",
      tw: "https://twitter.com/SuperTrompST",
      web: "https://tromponsols.com/",
      contractPresale: "9VURJAQtZaa2BkGCme7xxVnkCZkkvjZiDLtpLqq9gRpZ",
    },
    {
      id: 13123332,
      table: "akita",
      name: "Putin's Dog",
      logo: akita,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "The One Signal",
          icon: theone,
          link: "https://t.me/theone_signal",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "We bring innovation and confidence to you, ​join our community and let's make the new Akita Putin’s Dog on Solana!",
      min: 1,
      max: 4,
      time: "2024-03-05T15:00:00Z",
      totalRaised: 300,
      tele: "https://t.me/Putins_DogX",
      tw: "https://twitter.com/Putins_DogX",
      web: "https://putinsdogakita.com/",
      contractPresale: "GgWw6ZaszS4D1fNm3jCYF5UtBu2rxraUywPjYpazQHiF",
    },
    {
      id: 1312312,
      table: "fushipepe",
      name: "Fushi Pepe",
      logo: fushipepe,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "💸 Money Maker 💸",
          icon: MM,
          link: "https://t.me/Money_MakerMM",
        },
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Fushigidane + Pepe = Fushi Pepe.",
      min: 1,
      max: 4,
      time: "2024-03-04T15:00:00Z",
      totalRaised: 300,
      tele: "https://t.me/FushiPepe",
      tw: "https://twitter.com/FushiPepe",
      web: "https://fushipepe.xyz/",
      contractPresale: "7ytQVjCDn9tTxtgrodwtDjS84wW2dAcsnWvD1NhE9MiC",
    },
    {
      id: 1002131,
      table: "joewifhat",
      name: "Joewifhat",
      logo: joewifhat,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Hello my name is Joe and I have hat, some call me Joewifhat.",
      min: 1,
      max: 4,
      time: "2024-02-29T12:30:00Z",
      totalRaised: 300,
      tele: "https://t.me/Joewifhat_JOE",
      tw: "",
      web: "https://joewifhat.xyz/",
      contractPresale: "3VFp1La6EwFWWyry45h8xePrGprv16vzV2wGjG1uPB2T",
    },
    {
      id: 10032,
      table: "goldenpepewifhat",
      name: "Golden Pepewifhat",
      logo: goldenpepe,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "The cute SOL meme has arrived and will mark its territory on the Solana Chain.",
      min: 1,
      max: 5,
      time: "2024-02-26T12:20:00Z",
      totalRaised: 500,
      tele: "https://t.me/G_Pepewifhat",
      tw: "https://twitter.com/G_Pepewifhat",
      web: "https://goldenpepewifhat.info/",
      contractPresale: "AW2yGKAVyHGpUf7Suxox6d1KDKRthG9fB3ygPe6k2Q35",
    },
    {
      id: 1001,
      table: "moby",
      name: "MobyToken on Sol",
      logo: moby,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      whitelists: [
        "7iAbHb5bBfUWDpjEr5B6r7VdN7QJQ52L1qsaY2huoM9y",
        "5f5ofYkLQ5QGMdBJiZQrFEn4GzUC77od9g3jHr8pXocg",
        "5pcyxKQBncrEPf982mD9dncChLEtuwzZsgoZxobZsvBt",
        "BcpTqx8Dx9cq4tiaSgVsjGk1MyWmKzogucLM8hXvtWAe",
        "AHQ1bqpHpzmMNzfh49BFk6WdkSG8XRRjZ7ysA7xGzxu5",
        "BDAPWqZq8ngGqxGczqQ4J4qqrgtJdRJH8HJFj931SEY9",
        "ESfzgPmqfLsz7VtbCVZQ3edTKxjgWEyARjnuNFdDRHtd",
        "G7uLoWrYQAgBJa96sscv4yfohuHsZ49waaEHxg7czBXZ",
        "35tr4wiczyC8uZR1cbX5t7sLVJLBQbJxgCBVHRZY8fhs",
        "HwQK8UFnpVJ1C4THMp3poSmrNHVmZd3ZhLg5gFArHkAe",
        "myvEVBsqtWYEXaWkmqzyH9ZmaroKPHMx6rfGV8orpub",
        "Bd1Q3vMiCnkrAkTtmeA4egwRq1v2xkKWdXFVRmZiunFJ",
        "2XY2Nk3LpqVUCLWkqafaaCLcyhr6cEBttyEMj2X2aV8Z",
        "2k7uYKcCLsEqXvW94XoWyK1dgig7bY7cWnCcueqocATs",
        "6WhB63np6g19esTvi4qZf34MBB1G8tLxKv9A1RbZgYjU",
        "GaEtRXnDjP3SLo8jaFkomTp44Y3umcjbzMmkYEyZknmA",
        "5cJ2NmhTzRRiMvNKbvNjAfrfi8HKKcvvde3S2M4iY6U8",
        "5a6KhEAWZJvwnVEcgiJMUSPYFd7eR6KsvrXa9RfHnRKx",
        "GhWGDWfgnmFRZGNSZkBJVtsQYBrsnNhVa3KVcWRY9DVB",
        "46anwBMHbhM5PwtutoQ1T6aT3xEEDFK3qaDZ4kpw4w2Y",
        "GPWireGmiLoBCALFZKKTkPhQk8G4PxD5eqkyfSfn8mwd",
        "9iuqYhJRs5pvjp1C1RYaS3q1AFeJybfk71xMmyjZWt4i",
        "BxYBAMonUk9PbsK6xeKF3hhFJh5VKfdUmof444XrdPCC",
        "8dgbbJVwvus1fgem9vbu1EyHCGWhmyLGvpFZbYaeX9nc",
        "BkhsFyhse9WXN6d4Gz8dxxVMgazeM83nGi1LxT9XmLv6",
        "DWYyMuynbrAssa2dv9C9LDpMuWBFNe8UsHuR89L78FLk",
        "BYa3Q9rZZC5ygWkTyvibWXQjZArVQo4x5rwVgRSxtsGj",
        "3wvECvY7CBrdXAYR7Fj1mtizr1g96KzbK4Ee7cAgHvV4",
        "CqM55e5fpwyaFvF2pG7VRkaoGMf3siHQjXBpBLesGywS",
        "9qhZHWruU5mD8ngGzgmRccZrdum8Fxcv5w6TdUEfjEDQ",
        "Crpcc6cHmNKJFrV19vAzb4N6SCkLmMrm7vPSdLLJTWYf",
        "DKY8Ls15D5yZutPi3rnqvonEi3pWF9miP91KuP5F9eAf",
        "CsKuRZXZN1dmJBvZxvXEevCZhoKo83Z7JwGcLyzyvPNs",
        "7Uob14F2Huwfr5J5o1XpHhjKxstiggH5fXnM2uGYP3vm",
        "DH6QF1VGZxxncsTLHLNmsCBVZ2SQVzXVajS1uyeCVzSu",
        "FtkYNzgpWFoTFySGHTXqCNcvz6c2W5TD2w8DesxdJqrT",
        "8hWZ61NfMnKvCA4KC9KBUiFQRjMBwm1VpGsPiuJrFQCy",
        "DCuD2Yt4Gu6yPbJnihbXEwZWAiCua9Da12MngnhRxMwA",
        "GiGAbwpF5R1NE2dnPANrLo7JB7aFAfmhqFqLZrtap8eb",
        "5Da6vSRZBJh9CFHCsx65CKi9yTwcoY8xCr9TKSTfRFzG",
        "12jog5TjtweoPZA2rbBbRN9LjRk9FuxMYKjrPvAuzraM",
        "BgLrFpontCRRWKeqCCAPwhpPzTxg7KLCYQTYU2s24aM5",
        "6tY5ht1R7A9su8mQetznx9R467AFzHCevmr74pW4edFr",
        "71cCAqRmRR1ixgmdJC5inTPbyf8wCxQCGvQKa9zqRzoB",
        "GfkD1x4PNFNAxT3vW1r91GGwy6a92YDqK2v4KdQXM8nh",
        "r19ztdsgvNX3Y2ZS7zQBhaBziuRWY2t3eWSX1Cu4T1X",
        "6Vgd2eP34k5poMNDQVhUXiLmrpRXtwvgMkdPpKC8B3C1",
        "sKsJx3bbfAsuF9yy7v8o6cdwi7ndhJxLe6hD69roBgH",
        "fybLFYzJnjNuV8VmTGoiuFypFycssnVVHS3ce1kAoBP",
        "iYFdP9HaTxJxW6KA6DdXVRbLTa6GruPSSaZie5JZybj",
        "GnRr6tkz1KJQQh1dk1wde1q1VZQ7yKMZmyjooe5oqyzm",
        "93Ub4szkjGGqaXY1mEbqG5hH8R48GpdvLEQKeq8juFLP",
        "GGYzfA87s3Xi1d6j23BPgzcJM2E6Tw4SUVbnQnF5VLyA",
        "5YdjD9h9KfzoQ1H2oBGtiJQ9wYGx6qhnDZyKxED86TF2",
        "4NiMtHSP1jJZiVonShPJbsXi6UnhrP9YQZSefANPfoKu",
        "Fv4iuSTaEwDVDBF6SYmzrHpnADLUvsG3BcWdHXuc35QP",
        "9DGKSeZT2XDZvyfQEHKFtkt9ws5MFRS9SFpJN32RJniE",
        "3HEkp32Kn5yF1CUuuooCRgEwK5vdV2Sph6sEDNUqnjid",
        "HvuyALyxsGMBh9LevTRoJytCuMupe7BijHzzFDqmXpci",
        "9XSLort3zVHdcMssbN4UtocCgruEikd8pYc8zRPwHCKR",
        "AM6uoydiaEXGgD4Z9VbaoLEfY4YdksSLKEMDYckKVUkw",
        "AvMY6XfAKmLbR3CAtkmW2yHfk6rFzmriVEPUx8NNwcC6",
        "HxqeftgrcyqAf2SmDhBpcXr4ABTGE9NCnA2mheKNxFEe",
        "qcsFgmhPZFUtVVVAGqjuN2z4b6HmpecE9LrM68vmF4S",
        "KHDNdfSU14E2zscmF99XkUrEbCoG36z29hE82bYrK5M",
        "87wr6TisJxek8zFQQhkcS1HzfsxjCzxjmu5zSCiAj7zo",
        "CkURbHPZgs5C2XcsNjmmVNQkCYRVXatvJCFnAHaFox1n",
        "578DznJpYrgnK17gB3Z4UT822enFHLQApSChXudN63Tm",
        "E7XNp97D8kqwSHm45z2kk3pnYLR2xn3dnBs6cU9CbLuZ",
        "C2TztFm2QAA9feNw9mgAFWxpD5ZsFXZzMtFykqn45L1",
        "66Xk1s4X8VQ3QJpwoqt2DogV3BSin8rVYPaLYLEziLFz",
        "9VLdZ65M38Ydcwrsy6nt6sCEovbEb6iCNWSdCpiFhvpL",
        "HJr2i46vuoMZ1VtvEtVyFAcr7Vk1wnrcqN6sJvKrDYCA",
        "2wGRcxVKtVLV6QMGRJyq61cqVGyFMXKYecd88k9yhTbS",
        "E7yqRsmQVaXYzTpNFcXurubKccixUJmJYfe4NMjL2q3s",
        "6FP2trDsK66zKcFhSDoH4FDjfzGWvHTnuExNx4pn6Wsb",
        "EFspSeai7Yy5ys8fDxNqJ9rRxcFF7yo7aTz98ZgQYWEE",
        "JDuAV8kVBtkyQfMCm5XQBcsa6mbega2U5sgKm8NuXRBM",
        "N5Mh91r5qkAGWymvdnTdgJ6iYSiZhwRAEdGqW6mGrST",
        "EMbkioVRDiwtdM6BH6UMeu92zyhVRN6smUe26ZbAkxMq",
        "55QBTQbJyGbWy2JAxMmddQ29E7P1Egp1oJL5rRSSJzZa",
        "Ebc5qdqpVtrhkcz6vhZq5mkKvBM7xuHvLh3zQmaWv1VR",
        "47TAcFCJVVrZH16KyrZP1aYtUFxDNz9fycfdkA2Kza2g",
        "3PTh9SddoucUX1GaaBDN4EKQPPzcvaH4hfPM4mSmCfMw",
        "4FoZHPvAFgEFsJ4sHgQzrnj5PUbTDz6sNmHE3ZVnFnEt",
        "Ghfg1o4nsSammPfueizj5noVmEex1T77H1ZUAKhUmUcw",
        "7Sz6EdB43Ey87UeWMqxa7XiPTzRBHmYWgKFrggeVHmwp",
        "6AD3vEVgWbRDszxkJFFmxuNiErHFgxBMky8p4k5M94wb",
        "Fe71MXe8xQdSKMUWycWDqWprVzAv6GTux28JaiZwSAAE",
        "52mXkaugkay7Cg9bqPK6gSXjr5zqR9ptvMV6i53LgiW7",
        "BqvR1k5YZsFbsnXSk44Nh7RjWaBMtMt9jaXmvhadQ4BY",
        "BapbYynmYpt1Beptv1yNmr4Fgz9M8vZoyVJwZEHaDuew",
        "FNKdSuC1QNrkRdPwqx1c5eTr5PUpxqE6sXgXkzxDBPKb",
        "Gz6SjUVinHRFnCuFV9z9eqtvJr5c6nMcXbkYS6C4TDj",
        "5GmsNqFi3epwPemtM1frfTTwQotsReSAVatpEWpz3KGj",
        "Ftz7rcDXqA268bPooZqpMT5m5T36WbNjdyF985UpwQju",
        "4X64kLKkVKGkAJHApawe1MHUo8WvNygwxZKQyqxb6fus",
        "5fDPdo5J3iLCBSLsPw7yjRNgTRD8aeJRX3oMeXAr3sXG",
        "HbeUZG3KJCzMaTu399h6NQkmHqqkK3tVDmcuYGYo7eXt",
        "8pEKDnKCJocY2S2oorxh6cq2cv3wp1LALdhCWZCgHon5",
      ],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Moby emerges as a visionary platform in this turbulent landscape, with a mission to redefine the ICO paradigm.",
      min: 1,
      max: 3,
      time: "2024-02-23T12:30:00Z",
      totalRaised: 100000,
      tele: "https://t.me/MobyOnSol",
      tw: "https://twitter.com/MobyOnSol",
      web: "https://launchmobysol.xyz/",
      contractPresale: "4dxv35rJ2KES6RVnKBqqqmNpPapVEFwdQVx1HkfkTKcZ",
    },
    {
      id: 100,
      table: "pepeonmoon",
      name: "Pepe on Moon",
      logo: pepeonmoon,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Travel Caller",
          icon: travel,
          link: "https://t.me/TV_CALLS",
        },
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Pepe on Moon is a memecoin project aiming to bring the iconic Pepe meme to the world of cryptocurrency.",
      min: 1,
      max: 4,
      time: "2024-02-21T12:20:00Z",
      totalRaised: 100000,
      tele: "https://t.me/Pepe_on_Moon",
      tw: "https://twitter.com/Pepe_on_Moon",
      web: "https://pepeonmoon.xyz/",
      contractPresale: "89ZaJo4R6KWRWNm2WBxniXj2S67xXjQGp1TNDB1Vbobv",
    },
    {
      id: 100,
      table: "yellowsol",
      name: "Yellow",
      logo: yellow,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Panda Caller 🐼",
          icon: panda,
          link: "https://t.me/Panda_X1000",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "In the spectrum of colors, there exists a hue that embodies the essence of triumph and success - the vibrant shade of yellow.",
      min: 1,
      max: 5,
      time: "2024-02-19T12:00:00Z",
      totalRaised: 100000,
      tele: "https://t.me/yellow_solana",
      tw: "https://twitter.com/YellowSolana",
      web: "http://yellowsolana.xyz/",
      contractPresale: "BPZFajcCQ1FUUWfNzcTgP9RZYHdXvAmx3aasWGbVn7Yq",
    },
    {
      id: 2,
      table: "battlefight",
      name: "Battle Fight",
      logo: battle,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Unleash Your Inner Warrior: Battle Fight - Where Every Solo Duel Defines Legends!",
      min: 1,
      max: 5,
      time: "2024-02-01T12:20:00Z",
      totalRaised: 400,
      tele: "https://t.me/BattleFightCoin",
      tw: "https://twitter.com/BattleFightCoin",
      web: "https://battlefight.xyz/",
      contractPresale: "F3y5rR7xAUV8aEs2QkEsL1sGCYcFueNT7BHJJZq6zEcB",
    },
    {
      id: 2,
      table: "forsages",
      name: "Forsages",
      logo: forsages,
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
        {
          name: "Master Cat",
          icon: mastercat,
          link: "https://t.me/MasterCat_X",
        },
        {
          name: "Add more",
          icon: whitePlusIcon,
          link: "https://docs.idosol.me/2.-unique-features",
        },
      ],
      des: "Decentralized success, global empowerment! Join the revolution for financial freedom",
      min: 1,
      max: 5,
      time: "2024-01-23T13:20:00Z",
      totalRaised: 1000,
      tele: "https://t.me/Forsage_SOL",
      tw: "https://twitter.com/forsageofficial/",
      web: "https://forsages.io/",
      contractPresale: "2FuFYUJpPbmgN18CqUFKewn4yJQP4ZuYPLRbcbeimU63",
    },
    {
      id: 2,
      table: "maplestory",
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
      ],
      name: "MapleStory Finance",
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      logo: maple,
      des: "MapleStory Finance: Where Gaming Meets DeFi Magic – Unleashing Cuteness, Crafting Profits!",
      min: 1,
      max: 5,
      time: "2024-01-18T13:20:00Z",
      totalRaised: 500,
      tele: "https://t.me/MapleStoryX",
      tw: "https://twitter.com/MapleStory_X",
      web: "https://maplestoryfinance.me/",
      contractPresale: "75m95K4Jb1GbRfn4VX7NJ4X7jg2RCoAxudPFHdBgNTYt",
    },
    {
      id: 1,
      table: "fifa",
      marketing: [
        {
          name: "Memex9999",
          icon: meme,
          link: "https://t.me/memex9999call",
        },
      ],
      name: "ФИФА Заработай",
      tag: ["Safu", "Audit", "KYC", "Doxx"],
      logo: fifa,
      des: "Conquer the pitch with GameFi FIFA 2024: Where colors and passion collide!",
      min: 1,
      max: 5,
      time: "2024-01-15T13:20:00Z",
      totalRaised: 300,
      tele: "https://t.me/FifaEarnX",
      tw: "https://twitter.com/FifaEarnX",
      web: "https://fifaearn.pro/",
      contractPresale: "22ZNv9fUgY2uJTLt1Wkx8r8bNhJcrSzj89yjCVxanNR4",
    },
  ];
  const [dataTemp, dispatch] = useReducer(dataReducer, initialDataTemp);

  return (
    <DataContext.Provider value={{ dataTemp, dispatch }}>
      {children}
    </DataContext.Provider>
  );
};

export const useDataContext = () => {
  const context = useContext(DataContext);
  if (!context) {
    throw new Error("useDataContext must be used within a DataProvider");
  }
  return context;
};
